var annotated_dup =
[
    [ "Unravel", "namespace_unravel.html", [
      [ "Core", "namespace_unravel_1_1_core.html", [
        [ "AnimationClip", "class_unravel_1_1_core_1_1_animation_clip.html", null ],
        [ "AnimationComponent", "class_unravel_1_1_core_1_1_animation_component.html", "class_unravel_1_1_core_1_1_animation_component" ],
        [ "Asset", "class_unravel_1_1_core_1_1_asset.html", "class_unravel_1_1_core_1_1_asset" ],
        [ "Assets", "class_unravel_1_1_core_1_1_assets.html", null ],
        [ "AudioClip", "class_unravel_1_1_core_1_1_audio_clip.html", "class_unravel_1_1_core_1_1_audio_clip" ],
        [ "AudioListenerComponent", "class_unravel_1_1_core_1_1_audio_listener_component.html", null ],
        [ "AudioSourceComponent", "class_unravel_1_1_core_1_1_audio_source_component.html", "class_unravel_1_1_core_1_1_audio_source_component" ],
        [ "BoneComponent", "class_unravel_1_1_core_1_1_bone_component.html", null ],
        [ "CameraComponent", "class_unravel_1_1_core_1_1_camera_component.html", "class_unravel_1_1_core_1_1_camera_component" ],
        [ "Collision", "class_unravel_1_1_core_1_1_collision.html", "class_unravel_1_1_core_1_1_collision" ],
        [ "Component", "class_unravel_1_1_core_1_1_component.html", "class_unravel_1_1_core_1_1_component" ],
        [ "ContactPoint", "struct_unravel_1_1_core_1_1_contact_point.html", "struct_unravel_1_1_core_1_1_contact_point" ],
        [ "Entity", "struct_unravel_1_1_core_1_1_entity.html", "struct_unravel_1_1_core_1_1_entity" ],
        [ "FixedUpdateInfo", "struct_unravel_1_1_core_1_1_fixed_update_info.html", "struct_unravel_1_1_core_1_1_fixed_update_info" ],
        [ "Font", "class_unravel_1_1_core_1_1_font.html", null ],
        [ "IdComponent", "class_unravel_1_1_core_1_1_id_component.html", null ],
        [ "LayerMask", "struct_unravel_1_1_core_1_1_layer_mask.html", "struct_unravel_1_1_core_1_1_layer_mask" ],
        [ "LightComponent", "class_unravel_1_1_core_1_1_light_component.html", "class_unravel_1_1_core_1_1_light_component" ],
        [ "Material", "class_unravel_1_1_core_1_1_material.html", "class_unravel_1_1_core_1_1_material" ],
        [ "MaterialProperties", "struct_unravel_1_1_core_1_1_material_properties.html", "struct_unravel_1_1_core_1_1_material_properties" ],
        [ "MaxAttribute", "class_unravel_1_1_core_1_1_max_attribute.html", "class_unravel_1_1_core_1_1_max_attribute" ],
        [ "Mesh", "class_unravel_1_1_core_1_1_mesh.html", null ],
        [ "MinAttribute", "class_unravel_1_1_core_1_1_min_attribute.html", "class_unravel_1_1_core_1_1_min_attribute" ],
        [ "ModelComponent", "class_unravel_1_1_core_1_1_model_component.html", "class_unravel_1_1_core_1_1_model_component" ],
        [ "NativeObject", "class_unravel_1_1_core_1_1_native_object.html", "class_unravel_1_1_core_1_1_native_object" ],
        [ "PhysicsComponent", "class_unravel_1_1_core_1_1_physics_component.html", "class_unravel_1_1_core_1_1_physics_component" ],
        [ "PhysicsMaterial", "class_unravel_1_1_core_1_1_physics_material.html", null ],
        [ "Prefab", "class_unravel_1_1_core_1_1_prefab.html", null ],
        [ "RangeAttribute", "class_unravel_1_1_core_1_1_range_attribute.html", "class_unravel_1_1_core_1_1_range_attribute" ],
        [ "Ray", "struct_unravel_1_1_core_1_1_ray.html", "struct_unravel_1_1_core_1_1_ray" ],
        [ "RaycastHit", "struct_unravel_1_1_core_1_1_raycast_hit.html", "struct_unravel_1_1_core_1_1_raycast_hit" ],
        [ "ReflectionProbeComponent", "class_unravel_1_1_core_1_1_reflection_probe_component.html", null ],
        [ "Scene", "class_unravel_1_1_core_1_1_scene.html", null ],
        [ "ScriptComponent", "class_unravel_1_1_core_1_1_script_component.html", "class_unravel_1_1_core_1_1_script_component" ],
        [ "ScriptComponentManager", "class_unravel_1_1_core_1_1_script_component_manager.html", "class_unravel_1_1_core_1_1_script_component_manager" ],
        [ "ScriptSourceFileAttribute", "class_unravel_1_1_core_1_1_script_source_file_attribute.html", "class_unravel_1_1_core_1_1_script_source_file_attribute" ],
        [ "StepAttribute", "class_unravel_1_1_core_1_1_step_attribute.html", "class_unravel_1_1_core_1_1_step_attribute" ],
        [ "StyleSheet", "class_unravel_1_1_core_1_1_style_sheet.html", null ],
        [ "TextComponent", "class_unravel_1_1_core_1_1_text_component.html", "class_unravel_1_1_core_1_1_text_component" ],
        [ "Texture", "class_unravel_1_1_core_1_1_texture.html", null ],
        [ "TooltipAttribute", "class_unravel_1_1_core_1_1_tooltip_attribute.html", "class_unravel_1_1_core_1_1_tooltip_attribute" ],
        [ "TransformComponent", "class_unravel_1_1_core_1_1_transform_component.html", "class_unravel_1_1_core_1_1_transform_component" ],
        [ "UIChangeEvent", "class_unravel_1_1_core_1_1_u_i_change_event.html", "class_unravel_1_1_core_1_1_u_i_change_event" ],
        [ "UIDocument", "class_unravel_1_1_core_1_1_u_i_document.html", "class_unravel_1_1_core_1_1_u_i_document" ],
        [ "UIDocumentComponent", "class_unravel_1_1_core_1_1_u_i_document_component.html", "class_unravel_1_1_core_1_1_u_i_document_component" ],
        [ "UIElement", "class_unravel_1_1_core_1_1_u_i_element.html", "class_unravel_1_1_core_1_1_u_i_element" ],
        [ "UIEventBase", "class_unravel_1_1_core_1_1_u_i_event_base.html", "class_unravel_1_1_core_1_1_u_i_event_base" ],
        [ "UIKeyEvent", "class_unravel_1_1_core_1_1_u_i_key_event.html", "class_unravel_1_1_core_1_1_u_i_key_event" ],
        [ "UIPointerEvent", "class_unravel_1_1_core_1_1_u_i_pointer_event.html", "class_unravel_1_1_core_1_1_u_i_pointer_event" ],
        [ "UISliderEvent", "class_unravel_1_1_core_1_1_u_i_slider_event.html", "class_unravel_1_1_core_1_1_u_i_slider_event" ],
        [ "UITextInputEvent", "class_unravel_1_1_core_1_1_u_i_text_input_event.html", "class_unravel_1_1_core_1_1_u_i_text_input_event" ],
        [ "UpdateInfo", "struct_unravel_1_1_core_1_1_update_info.html", "struct_unravel_1_1_core_1_1_update_info" ],
        [ "VisualTree", "class_unravel_1_1_core_1_1_visual_tree.html", null ]
      ] ],
      [ "Samples", "namespace_unravel_1_1_samples.html", [
        [ "SampleUIWrapperController", "class_unravel_1_1_samples_1_1_sample_u_i_wrapper_controller.html", "class_unravel_1_1_samples_1_1_sample_u_i_wrapper_controller" ]
      ] ]
    ] ],
    [ "Bounds", "struct_bounds.html", "struct_bounds" ],
    [ "Color", "struct_color.html", "struct_color" ],
    [ "Mathf", "struct_mathf.html", "struct_mathf" ],
    [ "MathfInternal", "struct_mathf_internal.html", null ],
    [ "NewComponentTemplate", "class_new_component_template.html", "class_new_component_template" ],
    [ "Quaternion", "struct_quaternion.html", "struct_quaternion" ],
    [ "Range", "struct_range.html", "struct_range" ],
    [ "SampleMouseLookComponent", "class_sample_mouse_look_component.html", "class_sample_mouse_look_component" ],
    [ "SampleOrbitComponent", "class_sample_orbit_component.html", "class_sample_orbit_component" ],
    [ "Size", "struct_size.html", "struct_size" ],
    [ "Vector2", "struct_vector2.html", "struct_vector2" ],
    [ "Vector3", "struct_vector3.html", "struct_vector3" ],
    [ "Vector4", "struct_vector4.html", "struct_vector4" ]
];