var annotated_dup =
[
    [ "cmd_line", "namespacecmd__line.html", [
      [ "callback_args", "structcmd__line_1_1callback__args.html", "structcmd__line_1_1callback__args" ],
      [ "numeric_base", "classcmd__line_1_1numeric__base.html", "classcmd__line_1_1numeric__base" ],
      [ "parser", "classcmd__line_1_1parser.html", "classcmd__line_1_1parser" ]
    ] ],
    [ "fs", "namespacefs.html", [
      [ "cache", "classfs_1_1cache.html", "classfs_1_1cache" ],
      [ "pattern_filter", "classfs_1_1pattern__filter.html", "classfs_1_1pattern__filter" ],
      [ "stream_buffer", "structfs_1_1stream__buffer.html", "structfs_1_1stream__buffer" ],
      [ "syncer", "classfs_1_1syncer.html", "classfs_1_1syncer" ],
      [ "watcher", "classfs_1_1watcher.html", "classfs_1_1watcher" ],
      [ "wildcard_pattern", "classfs_1_1wildcard__pattern.html", "classfs_1_1wildcard__pattern" ]
    ] ],
    [ "GenerateIconFontCppHeaders", "namespace_generate_icon_font_cpp_headers.html", [
      [ "Font", "class_generate_icon_font_cpp_headers_1_1_font.html", "class_generate_icon_font_cpp_headers_1_1_font" ],
      [ "FontFA4", "class_generate_icon_font_cpp_headers_1_1_font_f_a4.html", "class_generate_icon_font_cpp_headers_1_1_font_f_a4" ],
      [ "FontFA5", "class_generate_icon_font_cpp_headers_1_1_font_f_a5.html", "class_generate_icon_font_cpp_headers_1_1_font_f_a5" ],
      [ "FontFA5Brands", "class_generate_icon_font_cpp_headers_1_1_font_f_a5_brands.html", "class_generate_icon_font_cpp_headers_1_1_font_f_a5_brands" ],
      [ "FontFK", "class_generate_icon_font_cpp_headers_1_1_font_f_k.html", null ],
      [ "FontII", "class_generate_icon_font_cpp_headers_1_1_font_i_i.html", "class_generate_icon_font_cpp_headers_1_1_font_i_i" ],
      [ "FontKI", "class_generate_icon_font_cpp_headers_1_1_font_k_i.html", "class_generate_icon_font_cpp_headers_1_1_font_k_i" ],
      [ "FontMD", "class_generate_icon_font_cpp_headers_1_1_font_m_d.html", "class_generate_icon_font_cpp_headers_1_1_font_m_d" ],
      [ "FontMDI", "class_generate_icon_font_cpp_headers_1_1_font_m_d_i.html", "class_generate_icon_font_cpp_headers_1_1_font_m_d_i" ],
      [ "Language", "class_generate_icon_font_cpp_headers_1_1_language.html", "class_generate_icon_font_cpp_headers_1_1_language" ],
      [ "LanguageC89", "class_generate_icon_font_cpp_headers_1_1_language_c89.html", "class_generate_icon_font_cpp_headers_1_1_language_c89" ],
      [ "LanguageCpp11", "class_generate_icon_font_cpp_headers_1_1_language_cpp11.html", "class_generate_icon_font_cpp_headers_1_1_language_cpp11" ],
      [ "LanguageCSharp", "class_generate_icon_font_cpp_headers_1_1_language_c_sharp.html", "class_generate_icon_font_cpp_headers_1_1_language_c_sharp" ]
    ] ],
    [ "generator", "namespacegenerator.html", [
      [ "detail", "namespacegenerator_1_1detail.html", [
        [ "box_corner_t", "classgenerator_1_1detail_1_1box__corner__t.html", "classgenerator_1_1detail_1_1box__corner__t" ],
        [ "box_corners_t", "classgenerator_1_1detail_1_1box__corners__t.html", "classgenerator_1_1detail_1_1box__corners__t" ],
        [ "box_edge_t", "classgenerator_1_1detail_1_1box__edge__t.html", "classgenerator_1_1detail_1_1box__edge__t" ],
        [ "box_edges_t", "classgenerator_1_1detail_1_1box__edges__t.html", "classgenerator_1_1detail_1_1box__edges__t" ],
        [ "box_face_t", "classgenerator_1_1detail_1_1box__face__t.html", "classgenerator_1_1detail_1_1box__face__t" ],
        [ "box_faces_t", "classgenerator_1_1detail_1_1box__faces__t.html", "classgenerator_1_1detail_1_1box__faces__t" ],
        [ "cap_t", "classgenerator_1_1detail_1_1cap__t.html", "classgenerator_1_1detail_1_1cap__t" ],
        [ "tube_cap_t", "classgenerator_1_1detail_1_1tube__cap__t.html", "classgenerator_1_1detail_1_1tube__cap__t" ]
      ] ],
      [ "any_generator", "classgenerator_1_1any__generator.html", "classgenerator_1_1any__generator" ],
      [ "any_mesh", "classgenerator_1_1any__mesh.html", "classgenerator_1_1any__mesh" ],
      [ "any_path", "classgenerator_1_1any__path.html", "classgenerator_1_1any__path" ],
      [ "any_shape", "classgenerator_1_1any__shape.html", "classgenerator_1_1any__shape" ],
      [ "axis_flip_mesh_t", "classgenerator_1_1axis__flip__mesh__t.html", "classgenerator_1_1axis__flip__mesh__t" ],
      [ "axis_swap_mesh_t", "classgenerator_1_1axis__swap__mesh__t.html", "classgenerator_1_1axis__swap__mesh__t" ],
      [ "axis_swap_path_t", "classgenerator_1_1axis__swap__path__t.html", "classgenerator_1_1axis__swap__path__t" ],
      [ "axis_swap_shape_t", "classgenerator_1_1axis__swap__shape__t.html", "classgenerator_1_1axis__swap__shape__t" ],
      [ "bezier_mesh_t", "classgenerator_1_1bezier__mesh__t.html", "classgenerator_1_1bezier__mesh__t" ],
      [ "bezier_shape_t", "classgenerator_1_1bezier__shape__t.html", "classgenerator_1_1bezier__shape__t" ],
      [ "box_mesh_t", "classgenerator_1_1box__mesh__t.html", "classgenerator_1_1box__mesh__t" ],
      [ "capped_cone_mesh_t", "classgenerator_1_1capped__cone__mesh__t.html", "classgenerator_1_1capped__cone__mesh__t" ],
      [ "capped_cylinder_mesh_t", "classgenerator_1_1capped__cylinder__mesh__t.html", "classgenerator_1_1capped__cylinder__mesh__t" ],
      [ "capped_tube_mesh_t", "classgenerator_1_1capped__tube__mesh__t.html", "classgenerator_1_1capped__tube__mesh__t" ],
      [ "capsule_mesh_t", "classgenerator_1_1capsule__mesh__t.html", "classgenerator_1_1capsule__mesh__t" ],
      [ "circle_shape_t", "classgenerator_1_1circle__shape__t.html", "classgenerator_1_1circle__shape__t" ],
      [ "cone_mesh_t", "classgenerator_1_1cone__mesh__t.html", "classgenerator_1_1cone__mesh__t" ],
      [ "convex_polygon_mesh_t", "classgenerator_1_1convex__polygon__mesh__t.html", "classgenerator_1_1convex__polygon__mesh__t" ],
      [ "cylinder_mesh_t", "classgenerator_1_1cylinder__mesh__t.html", "classgenerator_1_1cylinder__mesh__t" ],
      [ "disk_mesh_t", "classgenerator_1_1disk__mesh__t.html", "classgenerator_1_1disk__mesh__t" ],
      [ "dodecahedron_mesh_t", "classgenerator_1_1dodecahedron__mesh__t.html", "classgenerator_1_1dodecahedron__mesh__t" ],
      [ "edge_generator_type", "structgenerator_1_1edge__generator__type.html", "structgenerator_1_1edge__generator__type" ],
      [ "edge_generator_type< primitive_t, std::void_t< decltype(std::declval< const primitive_t >().edges())> >", "structgenerator_1_1edge__generator__type_3_01primitive__t_00_01std_1_1void__t_3_01decltype_07std8f458c3ec534b9b458ca444d504f0310.html", "structgenerator_1_1edge__generator__type_3_01primitive__t_00_01std_1_1void__t_3_01decltype_07std8f458c3ec534b9b458ca444d504f0310" ],
      [ "edge_t", "classgenerator_1_1edge__t.html", "classgenerator_1_1edge__t" ],
      [ "empty_mesh", "classgenerator_1_1empty__mesh.html", "classgenerator_1_1empty__mesh" ],
      [ "empty_path_t", "classgenerator_1_1empty__path__t.html", "classgenerator_1_1empty__path__t" ],
      [ "empty_shape_t", "classgenerator_1_1empty__shape__t.html", "classgenerator_1_1empty__shape__t" ],
      [ "extrude_mesh_t", "classgenerator_1_1extrude__mesh__t.html", "classgenerator_1_1extrude__mesh__t" ],
      [ "flip_mesh_t", "classgenerator_1_1flip__mesh__t.html", "classgenerator_1_1flip__mesh__t" ],
      [ "flip_path_t", "classgenerator_1_1flip__path__t.html", "classgenerator_1_1flip__path__t" ],
      [ "flip_shape_t", "classgenerator_1_1flip__shape__t.html", "classgenerator_1_1flip__shape__t" ],
      [ "gen_iterator_t", "classgenerator_1_1gen__iterator__t.html", "classgenerator_1_1gen__iterator__t" ],
      [ "generated_type", "structgenerator_1_1generated__type.html", "structgenerator_1_1generated__type" ],
      [ "generated_type< generator_t, std::void_t< decltype(std::declval< const generator_t >().generate())> >", "structgenerator_1_1generated__type_3_01generator__t_00_01std_1_1void__t_3_01decltype_07std_1_1de3f83968c01a25850db58e91762c2e5f4.html", "structgenerator_1_1generated__type_3_01generator__t_00_01std_1_1void__t_3_01decltype_07std_1_1de3f83968c01a25850db58e91762c2e5f4" ],
      [ "grid_shape_t", "classgenerator_1_1grid__shape__t.html", "classgenerator_1_1grid__shape__t" ],
      [ "helix_path_t", "classgenerator_1_1helix__path__t.html", "classgenerator_1_1helix__path__t" ],
      [ "ico_sphere_mesh_t", "classgenerator_1_1ico__sphere__mesh__t.html", "classgenerator_1_1ico__sphere__mesh__t" ],
      [ "icosahedron_mesh_t", "classgenerator_1_1icosahedron__mesh__t.html", "classgenerator_1_1icosahedron__mesh__t" ],
      [ "knot_path_t", "classgenerator_1_1knot__path__t.html", "classgenerator_1_1knot__path__t" ],
      [ "lathe_mesh_t", "classgenerator_1_1lathe__mesh__t.html", "classgenerator_1_1lathe__mesh__t" ],
      [ "line_path_t", "classgenerator_1_1line__path__t.html", "classgenerator_1_1line__path__t" ],
      [ "line_shape_t", "classgenerator_1_1line__shape__t.html", "classgenerator_1_1line__shape__t" ],
      [ "merge_mesh_t", "classgenerator_1_1merge__mesh__t.html", null ],
      [ "merge_mesh_t< Head, Tail... >", "classgenerator_1_1merge__mesh__t_3_01_head_00_01_tail_8_8_8_01_4.html", "classgenerator_1_1merge__mesh__t_3_01_head_00_01_tail_8_8_8_01_4" ],
      [ "merge_mesh_t<>", "classgenerator_1_1merge__mesh__t_3_4.html", null ],
      [ "merge_path_t", "classgenerator_1_1merge__path__t.html", null ],
      [ "merge_path_t< Head, Tail... >", "classgenerator_1_1merge__path__t_3_01_head_00_01_tail_8_8_8_01_4.html", "classgenerator_1_1merge__path__t_3_01_head_00_01_tail_8_8_8_01_4" ],
      [ "merge_path_t<>", "classgenerator_1_1merge__path__t_3_4.html", null ],
      [ "merge_shape_t", "classgenerator_1_1merge__shape__t.html", null ],
      [ "merge_shape_t< Head, Tail... >", "classgenerator_1_1merge__shape__t_3_01_head_00_01_tail_8_8_8_01_4.html", "classgenerator_1_1merge__shape__t_3_01_head_00_01_tail_8_8_8_01_4" ],
      [ "merge_shape_t<>", "classgenerator_1_1merge__shape__t_3_4.html", null ],
      [ "mesh_vertex_t", "classgenerator_1_1mesh__vertex__t.html", "classgenerator_1_1mesh__vertex__t" ],
      [ "mirror_mesh_t", "classgenerator_1_1mirror__mesh__t.html", "classgenerator_1_1mirror__mesh__t" ],
      [ "obj_writer_t", "classgenerator_1_1obj__writer__t.html", "classgenerator_1_1obj__writer__t" ],
      [ "parametric_mesh_t", "classgenerator_1_1parametric__mesh__t.html", "classgenerator_1_1parametric__mesh__t" ],
      [ "parametric_path_t", "classgenerator_1_1parametric__path__t.html", "classgenerator_1_1parametric__path__t" ],
      [ "parametric_shape_t", "classgenerator_1_1parametric__shape__t.html", "classgenerator_1_1parametric__shape__t" ],
      [ "path_vertex_t", "classgenerator_1_1path__vertex__t.html", "classgenerator_1_1path__vertex__t" ],
      [ "plane_mesh_t", "classgenerator_1_1plane__mesh__t.html", "classgenerator_1_1plane__mesh__t" ],
      [ "rectangle_shape_t", "classgenerator_1_1rectangle__shape__t.html", "classgenerator_1_1rectangle__shape__t" ],
      [ "repeat_mesh_t", "classgenerator_1_1repeat__mesh__t.html", "classgenerator_1_1repeat__mesh__t" ],
      [ "repeat_path_t", "classgenerator_1_1repeat__path__t.html", "classgenerator_1_1repeat__path__t" ],
      [ "repeat_shape_t", "classgenerator_1_1repeat__shape__t.html", "classgenerator_1_1repeat__shape__t" ],
      [ "rotate_mesh_t", "classgenerator_1_1rotate__mesh__t.html", "classgenerator_1_1rotate__mesh__t" ],
      [ "rotate_path_t", "classgenerator_1_1rotate__path__t.html", "classgenerator_1_1rotate__path__t" ],
      [ "rotate_shape_t", "classgenerator_1_1rotate__shape__t.html", "classgenerator_1_1rotate__shape__t" ],
      [ "rounded_box_mesh_t", "classgenerator_1_1rounded__box__mesh__t.html", "classgenerator_1_1rounded__box__mesh__t" ],
      [ "rounded_rectangle_shape_t", "classgenerator_1_1rounded__rectangle__shape__t.html", "classgenerator_1_1rounded__rectangle__shape__t" ],
      [ "scale_mesh_t", "classgenerator_1_1scale__mesh__t.html", "classgenerator_1_1scale__mesh__t" ],
      [ "scale_path_t", "classgenerator_1_1scale__path__t.html", "classgenerator_1_1scale__path__t" ],
      [ "scale_shape_t", "classgenerator_1_1scale__shape__t.html", "classgenerator_1_1scale__shape__t" ],
      [ "shape_to_path_t", "classgenerator_1_1shape__to__path__t.html", "classgenerator_1_1shape__to__path__t" ],
      [ "shape_vertex_t", "classgenerator_1_1shape__vertex__t.html", "classgenerator_1_1shape__vertex__t" ],
      [ "sphere_mesh_t", "classgenerator_1_1sphere__mesh__t.html", "classgenerator_1_1sphere__mesh__t" ],
      [ "spherical_cone_mesh_t", "classgenerator_1_1spherical__cone__mesh__t.html", "classgenerator_1_1spherical__cone__mesh__t" ],
      [ "spherical_triangle_mesh_t", "classgenerator_1_1spherical__triangle__mesh__t.html", "classgenerator_1_1spherical__triangle__mesh__t" ],
      [ "spherify_mesh_t", "classgenerator_1_1spherify__mesh__t.html", "classgenerator_1_1spherify__mesh__t" ],
      [ "spring_mesh_t", "classgenerator_1_1spring__mesh__t.html", "classgenerator_1_1spring__mesh__t" ],
      [ "subdivide_mesh_t", "classgenerator_1_1subdivide__mesh__t.html", "classgenerator_1_1subdivide__mesh__t" ],
      [ "subdivide_mesh_t< mesh_t, 0 >", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_010_01_4.html", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_010_01_4" ],
      [ "subdivide_mesh_t< mesh_t, 1 >", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_011_01_4.html", "classgenerator_1_1subdivide__mesh__t_3_01mesh__t_00_011_01_4" ],
      [ "subdivide_path_t", "classgenerator_1_1subdivide__path__t.html", "classgenerator_1_1subdivide__path__t" ],
      [ "subdivide_shape_t", "classgenerator_1_1subdivide__shape__t.html", "classgenerator_1_1subdivide__shape__t" ],
      [ "svg_writer_t", "classgenerator_1_1svg__writer__t.html", "classgenerator_1_1svg__writer__t" ],
      [ "teapot_mesh_t", "classgenerator_1_1teapot__mesh__t.html", "classgenerator_1_1teapot__mesh__t" ],
      [ "torus_knot_mesh_t", "classgenerator_1_1torus__knot__mesh__t.html", "classgenerator_1_1torus__knot__mesh__t" ],
      [ "torus_mesh_t", "classgenerator_1_1torus__mesh__t.html", "classgenerator_1_1torus__mesh__t" ],
      [ "transform_mesh_t", "classgenerator_1_1transform__mesh__t.html", "classgenerator_1_1transform__mesh__t" ],
      [ "transform_path_t", "classgenerator_1_1transform__path__t.html", "classgenerator_1_1transform__path__t" ],
      [ "transform_shape_t", "classgenerator_1_1transform__shape__t.html", "classgenerator_1_1transform__shape__t" ],
      [ "translate_mesh_t", "classgenerator_1_1translate__mesh__t.html", "classgenerator_1_1translate__mesh__t" ],
      [ "translate_path_t", "classgenerator_1_1translate__path__t.html", "classgenerator_1_1translate__path__t" ],
      [ "translate_shape_t", "classgenerator_1_1translate__shape__t.html", "classgenerator_1_1translate__shape__t" ],
      [ "triangle_generator_type", "structgenerator_1_1triangle__generator__type.html", "structgenerator_1_1triangle__generator__type" ],
      [ "triangle_generator_type< primitive_t, std::void_t< decltype(std::declval< const primitive_t >().triangles())> >", "structgenerator_1_1triangle__generator__type_3_01primitive__t_00_01std_1_1void__t_3_01decltype_01b9a814f2e80063a6453376d99a35411.html", "structgenerator_1_1triangle__generator__type_3_01primitive__t_00_01std_1_1void__t_3_01decltype_01b9a814f2e80063a6453376d99a35411" ],
      [ "triangle_mesh_t", "classgenerator_1_1triangle__mesh__t.html", "classgenerator_1_1triangle__mesh__t" ],
      [ "triangle_t", "classgenerator_1_1triangle__t.html", "classgenerator_1_1triangle__t" ],
      [ "tube_mesh_t", "classgenerator_1_1tube__mesh__t.html", "classgenerator_1_1tube__mesh__t" ],
      [ "uv_flip_mesh_t", "classgenerator_1_1uv__flip__mesh__t.html", "classgenerator_1_1uv__flip__mesh__t" ],
      [ "uv_swap_mesh_t", "classgenerator_1_1uv__swap__mesh__t.html", "classgenerator_1_1uv__swap__mesh__t" ],
      [ "vertex_generator_type", "structgenerator_1_1vertex__generator__type.html", "structgenerator_1_1vertex__generator__type" ],
      [ "vertex_generator_type< primitive_t, std::void_t< decltype(std::declval< const primitive_t >().vertices())> >", "structgenerator_1_1vertex__generator__type_3_01primitive__t_00_01std_1_1void__t_3_01decltype_07s0f912866fb87d3c56b026f8339da98d7.html", "structgenerator_1_1vertex__generator__type_3_01primitive__t_00_01std_1_1void__t_3_01decltype_07s0f912866fb87d3c56b026f8339da98d7" ]
    ] ],
    [ "gfx", "namespacegfx.html", [
      [ "Atlas", "classgfx_1_1_atlas.html", "classgfx_1_1_atlas" ],
      [ "AtlasRegion", "structgfx_1_1_atlas_region.html", "structgfx_1_1_atlas_region" ],
      [ "buffer_type", "structgfx_1_1buffer__type.html", "structgfx_1_1buffer__type" ],
      [ "clip_quad_def", "structgfx_1_1clip__quad__def.html", "structgfx_1_1clip__quad__def" ],
      [ "dd_raii", "structgfx_1_1dd__raii.html", "structgfx_1_1dd__raii" ],
      [ "fbo_attachment", "structgfx_1_1fbo__attachment.html", "structgfx_1_1fbo__attachment" ],
      [ "fbo_key", "structgfx_1_1fbo__key.html", "structgfx_1_1fbo__key" ],
      [ "font_info", "structgfx_1_1font__info.html", "structgfx_1_1font__info" ],
      [ "font_manager", "classgfx_1_1font__manager.html", "classgfx_1_1font__manager" ],
      [ "font_profile_scope", "structgfx_1_1font__profile__scope.html", "structgfx_1_1font__profile__scope" ],
      [ "format_details", "structgfx_1_1format__details.html", "structgfx_1_1format__details" ],
      [ "frame_buffer", "structgfx_1_1frame__buffer.html", "structgfx_1_1frame__buffer" ],
      [ "gfx_callback", "structgfx_1_1gfx__callback.html", "structgfx_1_1gfx__callback" ],
      [ "glyph_info", "structgfx_1_1glyph__info.html", "structgfx_1_1glyph__info" ],
      [ "handle_impl", "classgfx_1_1handle__impl.html", "classgfx_1_1handle__impl" ],
      [ "index_buffer", "structgfx_1_1index__buffer.html", "structgfx_1_1index__buffer" ],
      [ "mesh_vertex", "structgfx_1_1mesh__vertex.html", null ],
      [ "pos_texcoord0_color0_vertex", "structgfx_1_1pos__texcoord0__color0__vertex.html", null ],
      [ "pos_texcoord0_vertex", "structgfx_1_1pos__texcoord0__vertex.html", "structgfx_1_1pos__texcoord0__vertex" ],
      [ "pos_vertex", "structgfx_1_1pos__vertex.html", "structgfx_1_1pos__vertex" ],
      [ "program", "structgfx_1_1program.html", "structgfx_1_1program" ],
      [ "RectanglePacker", "classgfx_1_1_rectangle_packer.html", "classgfx_1_1_rectangle_packer" ],
      [ "render_pass", "structgfx_1_1render__pass.html", "structgfx_1_1render__pass" ],
      [ "render_view", "classgfx_1_1render__view.html", "classgfx_1_1render__view" ],
      [ "screen_pos_vertex", "structgfx_1_1screen__pos__vertex.html", "structgfx_1_1screen__pos__vertex" ],
      [ "shader", "structgfx_1_1shader.html", "structgfx_1_1shader" ],
      [ "text_buffer", "classgfx_1_1text__buffer.html", "classgfx_1_1text__buffer" ],
      [ "text_buffer_manager", "classgfx_1_1text__buffer__manager.html", "classgfx_1_1text__buffer__manager" ],
      [ "text_line_metrics", "classgfx_1_1text__line__metrics.html", "classgfx_1_1text__line__metrics" ],
      [ "text_metrics", "classgfx_1_1text__metrics.html", "classgfx_1_1text__metrics" ],
      [ "text_rectangle", "structgfx_1_1text__rectangle.html", "structgfx_1_1text__rectangle" ],
      [ "texture", "structgfx_1_1texture.html", "structgfx_1_1texture" ],
      [ "texture_key", "structgfx_1_1texture__key.html", "structgfx_1_1texture__key" ],
      [ "true_type_font", "classgfx_1_1true__type__font.html", "classgfx_1_1true__type__font" ],
      [ "uniform", "structgfx_1_1uniform.html", "structgfx_1_1uniform" ],
      [ "vertex", "structgfx_1_1vertex.html", null ],
      [ "vertex_buffer", "structgfx_1_1vertex__buffer.html", "structgfx_1_1vertex__buffer" ]
    ] ],
    [ "glm", "namespaceglm.html", [
      [ "detail", "namespaceglm_1_1detail.html", [
        [ "compute_to_string< math::transform_t< T, Q > >", "structglm_1_1detail_1_1compute__to__string_3_01math_1_1transform__t_3_01_t_00_01_q_01_4_01_4.html", null ]
      ] ]
    ] ],
    [ "gml", "namespacegml.html", [
      [ "detail", "namespacegml_1_1detail.html", [
        [ "bezierDerivativeImpl", "structgml_1_1detail_1_1bezier_derivative_impl.html", null ],
        [ "bezierDerivativeImpl< 0, 1, VecT, T >", "structgml_1_1detail_1_1bezier_derivative_impl_3_010_00_011_00_01_vec_t_00_01_t_01_4.html", null ],
        [ "bezierDerivativeImpl< 0, D, VecT, T >", "structgml_1_1detail_1_1bezier_derivative_impl_3_010_00_01_d_00_01_vec_t_00_01_t_01_4.html", null ],
        [ "bezierDerivativeImpl< O, 1, VecT, T >", "structgml_1_1detail_1_1bezier_derivative_impl_3_01_o_00_011_00_01_vec_t_00_01_t_01_4.html", null ]
      ] ]
    ] ],
    [ "helper", "namespacehelper.html", [
      [ "is_chrono_duration", "structhelper_1_1is__chrono__duration.html", null ],
      [ "is_chrono_duration< std::chrono::duration< R, P > >", "structhelper_1_1is__chrono__duration_3_01std_1_1chrono_1_1duration_3_01_r_00_01_p_01_4_01_4.html", null ]
    ] ],
    [ "ImBox", "namespace_im_box.html", [
      [ "MsgBox", "class_im_box_1_1_msg_box.html", "class_im_box_1_1_msg_box" ],
      [ "MsgBoxConfig", "struct_im_box_1_1_msg_box_config.html", "struct_im_box_1_1_msg_box_config" ],
      [ "MsgBoxManager", "class_im_box_1_1_msg_box_manager.html", "class_im_box_1_1_msg_box_manager" ]
    ] ],
    [ "ImGui", "namespace_im_gui.html", [
      [ "Font", "struct_im_gui_1_1_font.html", "struct_im_gui_1_1_font" ],
      [ "ImTexture", "union_im_gui_1_1_im_texture.html", "union_im_gui_1_1_im_texture" ]
    ] ],
    [ "input", "namespaceinput.html", [
      [ "action_map", "classinput_1_1action__map.html", "classinput_1_1action__map" ],
      [ "bimap", "classinput_1_1bimap.html", "classinput_1_1bimap" ],
      [ "button_state_map", "classinput_1_1button__state__map.html", "classinput_1_1button__state__map" ],
      [ "coord", "structinput_1_1coord.html", "structinput_1_1coord" ],
      [ "gamepad", "classinput_1_1gamepad.html", "classinput_1_1gamepad" ],
      [ "gamepad_360", "structinput_1_1gamepad__360.html", "structinput_1_1gamepad__360" ],
      [ "gamepad_action_map", "classinput_1_1gamepad__action__map.html", "classinput_1_1gamepad__action__map" ],
      [ "input_device", "classinput_1_1input__device.html", "classinput_1_1input__device" ],
      [ "input_manager", "classinput_1_1input__manager.html", "classinput_1_1input__manager" ],
      [ "input_reference_size", "structinput_1_1input__reference__size.html", "structinput_1_1input__reference__size" ],
      [ "key_state_map", "classinput_1_1key__state__map.html", "classinput_1_1key__state__map" ],
      [ "keyboard", "classinput_1_1keyboard.html", "classinput_1_1keyboard" ],
      [ "keyboard_action_map", "classinput_1_1keyboard__action__map.html", "classinput_1_1keyboard__action__map" ],
      [ "mouse", "classinput_1_1mouse.html", "classinput_1_1mouse" ],
      [ "mouse_action_map", "classinput_1_1mouse__action__map.html", "classinput_1_1mouse__action__map" ],
      [ "os_gamepad", "classinput_1_1os__gamepad.html", "classinput_1_1os__gamepad" ],
      [ "os_input_manager", "classinput_1_1os__input__manager.html", "classinput_1_1os__input__manager" ],
      [ "os_keyboard", "classinput_1_1os__keyboard.html", "classinput_1_1os__keyboard" ],
      [ "os_mouse", "classinput_1_1os__mouse.html", "classinput_1_1os__mouse" ],
      [ "point", "structinput_1_1point.html", "structinput_1_1point" ],
      [ "zone", "structinput_1_1zone.html", "structinput_1_1zone" ]
    ] ],
    [ "math", "namespacemath.html", [
      [ "bbox", "structmath_1_1bbox.html", "structmath_1_1bbox" ],
      [ "bsphere", "classmath_1_1bsphere.html", "classmath_1_1bsphere" ],
      [ "color", "structmath_1_1color.html", "structmath_1_1color" ],
      [ "frustum", "classmath_1_1frustum.html", "classmath_1_1frustum" ],
      [ "plane", "structmath_1_1plane.html", "structmath_1_1plane" ],
      [ "transform_t", "classmath_1_1transform__t.html", "classmath_1_1transform__t" ]
    ] ],
    [ "mono", "namespacemono.html", [
      [ "managed_interface", "namespacemono_1_1managed__interface.html", [
        [ "bbox", "structmono_1_1managed__interface_1_1bbox.html", "structmono_1_1managed__interface_1_1bbox" ],
        [ "color", "structmono_1_1managed__interface_1_1color.html", "structmono_1_1managed__interface_1_1color" ],
        [ "material_properties", "structmono_1_1managed__interface_1_1material__properties.html", "structmono_1_1managed__interface_1_1material__properties" ],
        [ "quaternion", "structmono_1_1managed__interface_1_1quaternion.html", "structmono_1_1managed__interface_1_1quaternion" ],
        [ "ray", "structmono_1_1managed__interface_1_1ray.html", "structmono_1_1managed__interface_1_1ray" ],
        [ "raycast_hit", "structmono_1_1managed__interface_1_1raycast__hit.html", "structmono_1_1managed__interface_1_1raycast__hit" ],
        [ "ui_change_event", "structmono_1_1managed__interface_1_1ui__change__event.html", "structmono_1_1managed__interface_1_1ui__change__event" ],
        [ "ui_event_base", "structmono_1_1managed__interface_1_1ui__event__base.html", "structmono_1_1managed__interface_1_1ui__event__base" ],
        [ "ui_key_event", "structmono_1_1managed__interface_1_1ui__key__event.html", "structmono_1_1managed__interface_1_1ui__key__event" ],
        [ "ui_pointer_event", "structmono_1_1managed__interface_1_1ui__pointer__event.html", "structmono_1_1managed__interface_1_1ui__pointer__event" ],
        [ "ui_slider_event", "structmono_1_1managed__interface_1_1ui__slider__event.html", "structmono_1_1managed__interface_1_1ui__slider__event" ],
        [ "ui_textinput_event", "structmono_1_1managed__interface_1_1ui__textinput__event.html", "structmono_1_1managed__interface_1_1ui__textinput__event" ],
        [ "vector2", "structmono_1_1managed__interface_1_1vector2.html", "structmono_1_1managed__interface_1_1vector2" ],
        [ "vector3", "structmono_1_1managed__interface_1_1vector3.html", "structmono_1_1managed__interface_1_1vector3" ],
        [ "vector4", "structmono_1_1managed__interface_1_1vector4.html", "structmono_1_1managed__interface_1_1vector4" ]
      ] ],
      [ "mono_converter< hpp::small_vector< T, StaticCapacity > >", "structmono_1_1mono__converter_3_01hpp_1_1small__vector_3_01_t_00_01_static_capacity_01_4_01_4.html", "structmono_1_1mono__converter_3_01hpp_1_1small__vector_3_01_t_00_01_static_capacity_01_4_01_4" ],
      [ "mono_converter< managed_interface::ui_change_event >", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__change__event_01_4.html", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__change__event_01_4" ],
      [ "mono_converter< managed_interface::ui_event_base >", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__event__base_01_4.html", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__event__base_01_4" ],
      [ "mono_converter< managed_interface::ui_key_event >", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__key__event_01_4.html", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__key__event_01_4" ],
      [ "mono_converter< managed_interface::ui_pointer_event >", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__pointer__event_01_4.html", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__pointer__event_01_4" ],
      [ "mono_converter< managed_interface::ui_slider_event >", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__slider__event_01_4.html", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__slider__event_01_4" ],
      [ "mono_converter< managed_interface::ui_textinput_event >", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__textinput__event_01_4.html", "structmono_1_1mono__converter_3_01managed__interface_1_1ui__textinput__event_01_4" ]
    ] ],
    [ "moodycamel", "namespacemoodycamel.html", [
      [ "details", "namespacemoodycamel_1_1details.html", [
        [ "_hash_32_or_64", "structmoodycamel_1_1details_1_1__hash__32__or__64.html", null ],
        [ "_hash_32_or_64< 1 >", "structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4.html", null ],
        [ "ConcurrentQueueProducerTypelessBase", "structmoodycamel_1_1details_1_1_concurrent_queue_producer_typeless_base.html", "structmoodycamel_1_1details_1_1_concurrent_queue_producer_typeless_base" ],
        [ "const_numeric_max", "structmoodycamel_1_1details_1_1const__numeric__max.html", null ],
        [ "hash_32_or_64", "structmoodycamel_1_1details_1_1hash__32__or__64.html", null ],
        [ "identity", "structmoodycamel_1_1details_1_1identity.html", "structmoodycamel_1_1details_1_1identity" ],
        [ "is_trivially_destructible", "structmoodycamel_1_1details_1_1is__trivially__destructible.html", null ],
        [ "max_align_t", "unionmoodycamel_1_1details_1_1max__align__t.html", "unionmoodycamel_1_1details_1_1max__align__t" ],
        [ "nomove_if", "structmoodycamel_1_1details_1_1nomove__if.html", null ],
        [ "nomove_if< false >", "structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4.html", null ],
        [ "static_is_lock_free", "structmoodycamel_1_1details_1_1static__is__lock__free.html", null ],
        [ "static_is_lock_free< bool >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01bool_01_4.html", null ],
        [ "static_is_lock_free< U * >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01_u_01_5_01_4.html", null ],
        [ "static_is_lock_free_num", "structmoodycamel_1_1details_1_1static__is__lock__free__num.html", null ],
        [ "static_is_lock_free_num< int >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01int_01_4.html", null ],
        [ "static_is_lock_free_num< long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01_4.html", null ],
        [ "static_is_lock_free_num< long long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01long_01_4.html", null ],
        [ "static_is_lock_free_num< short >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01short_01_4.html", null ],
        [ "static_is_lock_free_num< signed char >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01signed_01char_01_4.html", null ],
        [ "thread_id_converter", "structmoodycamel_1_1details_1_1thread__id__converter.html", "structmoodycamel_1_1details_1_1thread__id__converter" ],
        [ "ThreadExitListener", "structmoodycamel_1_1details_1_1_thread_exit_listener.html", "structmoodycamel_1_1details_1_1_thread_exit_listener" ],
        [ "ThreadExitNotifier", "classmoodycamel_1_1details_1_1_thread_exit_notifier.html", null ]
      ] ],
      [ "BlockingConcurrentQueue", "classmoodycamel_1_1_blocking_concurrent_queue.html", null ],
      [ "ConcurrentQueue", "classmoodycamel_1_1_concurrent_queue.html", "classmoodycamel_1_1_concurrent_queue" ],
      [ "ConcurrentQueueDefaultTraits", "structmoodycamel_1_1_concurrent_queue_default_traits.html", "structmoodycamel_1_1_concurrent_queue_default_traits" ],
      [ "ConsumerToken", "structmoodycamel_1_1_consumer_token.html", "structmoodycamel_1_1_consumer_token" ],
      [ "ProducerToken", "structmoodycamel_1_1_producer_token.html", "structmoodycamel_1_1_producer_token" ]
    ] ],
    [ "rtti", "namespacertti.html", [
      [ "context", "structrtti_1_1context.html", "structrtti_1_1context" ]
    ] ],
    [ "seq", "namespaceseq.html", [
      [ "seq_action", "structseq_1_1seq__action.html", "structseq_1_1seq__action" ],
      [ "seq_inspect_info", "structseq_1_1seq__inspect__info.html", "structseq_1_1seq__inspect__info" ],
      [ "seq_manager", "structseq_1_1seq__manager.html", "structseq_1_1seq__manager" ],
      [ "seq_private", "structseq_1_1seq__private.html", null ],
      [ "seq_scope_policy", "structseq_1_1seq__scope__policy.html", "structseq_1_1seq__scope__policy" ],
      [ "values_t", "structseq_1_1values__t.html", "structseq_1_1values__t" ]
    ] ],
    [ "ser20", "namespaceser20.html", [
      [ "variant_detail", "namespaceser20_1_1variant__detail.html", [
        [ "variant_save_visitor", "structser20_1_1variant__detail_1_1variant__save__visitor.html", "structser20_1_1variant__detail_1_1variant__save__visitor" ]
      ] ],
      [ "basic_handle_link", "structser20_1_1basic__handle__link.html", "structser20_1_1basic__handle__link" ],
      [ "const_entity_handle_link", "structser20_1_1const__entity__handle__link.html", null ],
      [ "entity_handle_link", "structser20_1_1entity__handle__link.html", null ],
      [ "membuf", "classser20_1_1membuf.html", "classser20_1_1membuf" ],
      [ "YAMLInputArchive", "classser20_1_1_y_a_m_l_input_archive.html", "classser20_1_1_y_a_m_l_input_archive" ],
      [ "YAMLOutputArchive", "classser20_1_1_y_a_m_l_output_archive.html", "classser20_1_1_y_a_m_l_output_archive" ]
    ] ],
    [ "serialization", "namespaceserialization.html", [
      [ "path_context", "structserialization_1_1path__context.html", "structserialization_1_1path__context" ],
      [ "path_segment_guard", "structserialization_1_1path__segment__guard.html", "structserialization_1_1path__segment__guard" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< contact_key >", "structstd_1_1hash_3_01contact__key_01_4.html", "structstd_1_1hash_3_01contact__key_01_4" ],
      [ "hash< gfx::fbo_key >", "structstd_1_1hash_3_01gfx_1_1fbo__key_01_4.html", "structstd_1_1hash_3_01gfx_1_1fbo__key_01_4" ],
      [ "hash< gfx::texture_key >", "structstd_1_1hash_3_01gfx_1_1texture__key_01_4.html", "structstd_1_1hash_3_01gfx_1_1texture__key_01_4" ]
    ] ],
    [ "subprocess", "namespacesubprocess.html", [
      [ "call_result", "structsubprocess_1_1call__result.html", "structsubprocess_1_1call__result" ]
    ] ],
    [ "unravel", "namespaceunravel.html", [
      [ "asset_compiler", "namespaceunravel_1_1asset__compiler.html", [
        [ "script_compilation_entry", "structunravel_1_1asset__compiler_1_1script__compilation__entry.html", "structunravel_1_1asset__compiler_1_1script__compilation__entry" ]
      ] ],
      [ "crash", "namespaceunravel_1_1crash.html", [
        [ "crash_handlers", "structunravel_1_1crash_1_1crash__handlers.html", "structunravel_1_1crash_1_1crash__handlers" ],
        [ "exception_info", "structunravel_1_1crash_1_1exception__info.html", "structunravel_1_1crash_1_1exception__info" ],
        [ "signal_info", "structunravel_1_1crash_1_1signal__info.html", "structunravel_1_1crash_1_1signal__info" ],
        [ "trace_info", "structunravel_1_1crash_1_1trace__info.html", "structunravel_1_1crash_1_1trace__info" ]
      ] ],
      [ "detail", "namespaceunravel_1_1detail.html", [
        [ "sun_controller", "classunravel_1_1detail_1_1sun__controller.html", "classunravel_1_1detail_1_1sun__controller" ]
      ] ],
      [ "importer", "namespaceunravel_1_1importer.html", [
        [ "imported_material", "structunravel_1_1importer_1_1imported__material.html", "structunravel_1_1importer_1_1imported__material" ],
        [ "imported_texture", "structunravel_1_1importer_1_1imported__texture.html", "structunravel_1_1importer_1_1imported__texture" ]
      ] ],
      [ "rendering", "namespaceunravel_1_1rendering.html", [
        [ "deferred", "classunravel_1_1rendering_1_1deferred.html", "classunravel_1_1rendering_1_1deferred" ],
        [ "lod_data", "structunravel_1_1rendering_1_1lod__data.html", "structunravel_1_1rendering_1_1lod__data" ],
        [ "per_camera_data", "structunravel_1_1rendering_1_1per__camera__data.html", "structunravel_1_1rendering_1_1per__camera__data" ],
        [ "pipeline", "classunravel_1_1rendering_1_1pipeline.html", "classunravel_1_1rendering_1_1pipeline" ]
      ] ],
      [ "shadow", "namespaceunravel_1_1shadow.html", [
        [ "adaptive_shadow_params", "structunravel_1_1shadow_1_1adaptive__shadow__params.html", "structunravel_1_1shadow_1_1adaptive__shadow__params" ],
        [ "ClearValues", "structunravel_1_1shadow_1_1_clear_values.html", "structunravel_1_1shadow_1_1_clear_values" ],
        [ "csm_optimization_flags", "structunravel_1_1shadow_1_1csm__optimization__flags.html", "structunravel_1_1shadow_1_1csm__optimization__flags" ],
        [ "DepthImpl", "structunravel_1_1shadow_1_1_depth_impl.html", "structunravel_1_1shadow_1_1_depth_impl" ],
        [ "frustum_calculation_method", "structunravel_1_1shadow_1_1frustum__calculation__method.html", "structunravel_1_1shadow_1_1frustum__calculation__method" ],
        [ "Light", "structunravel_1_1shadow_1_1_light.html", "structunravel_1_1shadow_1_1_light" ],
        [ "LightType", "structunravel_1_1shadow_1_1_light_type.html", "structunravel_1_1shadow_1_1_light_type" ],
        [ "PackDepth", "structunravel_1_1shadow_1_1_pack_depth.html", "structunravel_1_1shadow_1_1_pack_depth" ],
        [ "PosColorTexCoord0Vertex", "structunravel_1_1shadow_1_1_pos_color_tex_coord0_vertex.html", "structunravel_1_1shadow_1_1_pos_color_tex_coord0_vertex" ],
        [ "PosNormalTexcoordVertex", "structunravel_1_1shadow_1_1_pos_normal_texcoord_vertex.html", "structunravel_1_1shadow_1_1_pos_normal_texcoord_vertex" ],
        [ "PosVertex", "structunravel_1_1shadow_1_1_pos_vertex.html", "structunravel_1_1shadow_1_1_pos_vertex" ],
        [ "Programs", "structunravel_1_1shadow_1_1_programs.html", "structunravel_1_1shadow_1_1_programs" ],
        [ "ProjType", "structunravel_1_1shadow_1_1_proj_type.html", "structunravel_1_1shadow_1_1_proj_type" ],
        [ "RenderState", "structunravel_1_1shadow_1_1_render_state.html", "structunravel_1_1shadow_1_1_render_state" ],
        [ "SceneSettings", "structunravel_1_1shadow_1_1_scene_settings.html", "structunravel_1_1shadow_1_1_scene_settings" ],
        [ "shadowmap_generator", "classunravel_1_1shadow_1_1shadowmap__generator.html", "classunravel_1_1shadow_1_1shadowmap__generator" ],
        [ "ShadowMapRenderTargets", "structunravel_1_1shadow_1_1_shadow_map_render_targets.html", "structunravel_1_1shadow_1_1_shadow_map_render_targets" ],
        [ "ShadowMapSettings", "structunravel_1_1shadow_1_1_shadow_map_settings.html", "structunravel_1_1shadow_1_1_shadow_map_settings" ],
        [ "SmImpl", "structunravel_1_1shadow_1_1_sm_impl.html", "structunravel_1_1shadow_1_1_sm_impl" ],
        [ "SmType", "structunravel_1_1shadow_1_1_sm_type.html", "structunravel_1_1shadow_1_1_sm_type" ],
        [ "TetrahedronFaces", "structunravel_1_1shadow_1_1_tetrahedron_faces.html", "structunravel_1_1shadow_1_1_tetrahedron_faces" ],
        [ "Uniforms", "structunravel_1_1shadow_1_1_uniforms.html", "structunravel_1_1shadow_1_1_uniforms" ]
      ] ],
      [ "statistics_utils", "namespaceunravel_1_1statistics__utils.html", [
        [ "sample_data", "classunravel_1_1statistics__utils_1_1sample__data.html", "classunravel_1_1statistics__utils_1_1sample__data" ]
      ] ],
      [ "active_component", "structunravel_1_1active__component.html", null ],
      [ "alignment", "structunravel_1_1alignment.html", "structunravel_1_1alignment" ],
      [ "animation_channel", "structunravel_1_1animation__channel.html", "structunravel_1_1animation__channel" ],
      [ "animation_clip", "structunravel_1_1animation__clip.html", "structunravel_1_1animation__clip" ],
      [ "animation_component", "classunravel_1_1animation__component.html", "classunravel_1_1animation__component" ],
      [ "animation_importer_meta", "structunravel_1_1animation__importer__meta.html", "structunravel_1_1animation__importer__meta" ],
      [ "animation_panel", "classunravel_1_1animation__panel.html", "classunravel_1_1animation__panel" ],
      [ "animation_player", "classunravel_1_1animation__player.html", "classunravel_1_1animation__player" ],
      [ "animation_pose", "structunravel_1_1animation__pose.html", "structunravel_1_1animation__pose" ],
      [ "animation_state", "structunravel_1_1animation__state.html", "structunravel_1_1animation__state" ],
      [ "animation_system", "classunravel_1_1animation__system.html", "classunravel_1_1animation__system" ],
      [ "assao_component", "classunravel_1_1assao__component.html", "classunravel_1_1assao__component" ],
      [ "assao_pass", "classunravel_1_1assao__pass.html", "classunravel_1_1assao__pass" ],
      [ "asset_database", "classunravel_1_1asset__database.html", "classunravel_1_1asset__database" ],
      [ "asset_importer_meta", "structunravel_1_1asset__importer__meta.html", "structunravel_1_1asset__importer__meta" ],
      [ "asset_manager", "classunravel_1_1asset__manager.html", "classunravel_1_1asset__manager" ],
      [ "asset_meta", "structunravel_1_1asset__meta.html", "structunravel_1_1asset__meta" ],
      [ "asset_storage", "structunravel_1_1asset__storage.html", "structunravel_1_1asset__storage" ],
      [ "asset_watcher", "classunravel_1_1asset__watcher.html", "classunravel_1_1asset__watcher" ],
      [ "atmospheric_pass", "classunravel_1_1atmospheric__pass.html", "classunravel_1_1atmospheric__pass" ],
      [ "atmospheric_pass_perez", "classunravel_1_1atmospheric__pass__perez.html", "classunravel_1_1atmospheric__pass__perez" ],
      [ "atmospheric_pass_skybox", "classunravel_1_1atmospheric__pass__skybox.html", "classunravel_1_1atmospheric__pass__skybox" ],
      [ "audio_clip", "structunravel_1_1audio__clip.html", "structunravel_1_1audio__clip" ],
      [ "audio_importer_meta", "structunravel_1_1audio__importer__meta.html", "structunravel_1_1audio__importer__meta" ],
      [ "audio_listener_component", "classunravel_1_1audio__listener__component.html", "classunravel_1_1audio__listener__component" ],
      [ "audio_source_component", "classunravel_1_1audio__source__component.html", "classunravel_1_1audio__source__component" ],
      [ "audio_system", "classunravel_1_1audio__system.html", "classunravel_1_1audio__system" ],
      [ "base_font", "structunravel_1_1base__font.html", "structunravel_1_1base__font" ],
      [ "basic_component", "structunravel_1_1basic__component.html", "structunravel_1_1basic__component" ],
      [ "basic_storage", "structunravel_1_1basic__storage.html", "structunravel_1_1basic__storage" ],
      [ "blend_over_param", "structunravel_1_1blend__over__param.html", "structunravel_1_1blend__over__param" ],
      [ "blend_over_time", "structunravel_1_1blend__over__time.html", "structunravel_1_1blend__over__time" ],
      [ "blend_space_def", "classunravel_1_1blend__space__def.html", "classunravel_1_1blend__space__def" ],
      [ "blend_space_point", "structunravel_1_1blend__space__point.html", "structunravel_1_1blend__space__point" ],
      [ "blend_state", "structunravel_1_1blend__state.html", "structunravel_1_1blend__state" ],
      [ "blit_pass", "classunravel_1_1blit__pass.html", "classunravel_1_1blit__pass" ],
      [ "bone_component", "structunravel_1_1bone__component.html", "structunravel_1_1bone__component" ],
      [ "bone_palette", "classunravel_1_1bone__palette.html", "classunravel_1_1bone__palette" ],
      [ "bullet_backend", "structunravel_1_1bullet__backend.html", "structunravel_1_1bullet__backend" ],
      [ "camera", "classunravel_1_1camera.html", "classunravel_1_1camera" ],
      [ "camera_component", "classunravel_1_1camera__component.html", "classunravel_1_1camera__component" ],
      [ "camera_storage", "structunravel_1_1camera__storage.html", "structunravel_1_1camera__storage" ],
      [ "camera_system", "classunravel_1_1camera__system.html", "classunravel_1_1camera__system" ],
      [ "camera_updated_tag", "structunravel_1_1camera__updated__tag.html", null ],
      [ "compiled_resource_manager", "classunravel_1_1compiled__resource__manager.html", "classunravel_1_1compiled__resource__manager" ],
      [ "component_crtp", "structunravel_1_1component__crtp.html", "structunravel_1_1component__crtp" ],
      [ "component_meta", "structunravel_1_1component__meta.html", null ],
      [ "composite_action_t", "structunravel_1_1composite__action__t.html", "structunravel_1_1composite__action__t" ],
      [ "console_log_panel", "classunravel_1_1console__log__panel.html", "classunravel_1_1console__log__panel" ],
      [ "content_browser_item", "structunravel_1_1content__browser__item.html", "structunravel_1_1content__browser__item" ],
      [ "content_browser_panel", "classunravel_1_1content__browser__panel.html", "classunravel_1_1content__browser__panel" ],
      [ "defaults", "structunravel_1_1defaults.html", "structunravel_1_1defaults" ],
      [ "deploy", "structunravel_1_1deploy.html", null ],
      [ "deploy_panel", "classunravel_1_1deploy__panel.html", "classunravel_1_1deploy__panel" ],
      [ "deploy_settings", "structunravel_1_1deploy__settings.html", "structunravel_1_1deploy__settings" ],
      [ "dockspace", "classunravel_1_1dockspace.html", "classunravel_1_1dockspace" ],
      [ "ecs", "structunravel_1_1ecs.html", "structunravel_1_1ecs" ],
      [ "editing_action_t", "structunravel_1_1editing__action__t.html", "structunravel_1_1editing__action__t" ],
      [ "editing_manager", "structunravel_1_1editing__manager.html", "structunravel_1_1editing__manager" ],
      [ "editor", "structunravel_1_1editor.html", null ],
      [ "editor_actions", "structunravel_1_1editor__actions.html", null ],
      [ "editor_settings", "structunravel_1_1editor__settings.html", "structunravel_1_1editor__settings" ],
      [ "editor_settings_panel", "classunravel_1_1editor__settings__panel.html", "classunravel_1_1editor__settings__panel" ],
      [ "engine", "structunravel_1_1engine.html", null ],
      [ "entity_add_component_action_t", "structunravel_1_1entity__add__component__action__t.html", "structunravel_1_1entity__add__component__action__t" ],
      [ "entity_add_script_component_action_t", "structunravel_1_1entity__add__script__component__action__t.html", "structunravel_1_1entity__add__script__component__action__t" ],
      [ "entity_components", "structunravel_1_1entity__components.html", "structunravel_1_1entity__components" ],
      [ "entity_data", "structunravel_1_1entity__data.html", "structunravel_1_1entity__data" ],
      [ "entity_panel", "classunravel_1_1entity__panel.html", "classunravel_1_1entity__panel" ],
      [ "entity_remove_component_action_t", "structunravel_1_1entity__remove__component__action__t.html", "structunravel_1_1entity__remove__component__action__t" ],
      [ "entity_remove_script_component_action_t", "structunravel_1_1entity__remove__script__component__action__t.html", "structunravel_1_1entity__remove__script__component__action__t" ],
      [ "entity_set_active_action_t", "structunravel_1_1entity__set__active__action__t.html", "structunravel_1_1entity__set__active__action__t" ],
      [ "entity_set_materials_action_t", "structunravel_1_1entity__set__materials__action__t.html", "structunravel_1_1entity__set__materials__action__t" ],
      [ "entity_set_name_action_t", "structunravel_1_1entity__set__name__action__t.html", "structunravel_1_1entity__set__name__action__t" ],
      [ "entity_set_tag_action_t", "structunravel_1_1entity__set__tag__action__t.html", "structunravel_1_1entity__set__tag__action__t" ],
      [ "entity_set_text_bounds_action_t", "structunravel_1_1entity__set__text__bounds__action__t.html", "structunravel_1_1entity__set__text__bounds__action__t" ],
      [ "events", "structunravel_1_1events.html", "structunravel_1_1events" ],
      [ "font", "structunravel_1_1font.html", "structunravel_1_1font" ],
      [ "footer_panel", "classunravel_1_1footer__panel.html", "classunravel_1_1footer__panel" ],
      [ "frag_atom", "structunravel_1_1frag__atom.html", "structunravel_1_1frag__atom" ],
      [ "fxaa_component", "classunravel_1_1fxaa__component.html", "classunravel_1_1fxaa__component" ],
      [ "fxaa_pass", "classunravel_1_1fxaa__pass.html", "classunravel_1_1fxaa__pass" ],
      [ "game_panel", "classunravel_1_1game__panel.html", "classunravel_1_1game__panel" ],
      [ "gizmo", "structunravel_1_1gizmo.html", "structunravel_1_1gizmo" ],
      [ "gizmo_entity", "structunravel_1_1gizmo__entity.html", "structunravel_1_1gizmo__entity" ],
      [ "gizmo_physics_component", "structunravel_1_1gizmo__physics__component.html", "structunravel_1_1gizmo__physics__component" ],
      [ "gizmo_registry", "structunravel_1_1gizmo__registry.html", "structunravel_1_1gizmo__registry" ],
      [ "gizmos_renderer", "classunravel_1_1gizmos__renderer.html", "classunravel_1_1gizmos__renderer" ],
      [ "gpu_program", "classunravel_1_1gpu__program.html", "classunravel_1_1gpu__program" ],
      [ "header_panel", "classunravel_1_1header__panel.html", "classunravel_1_1header__panel" ],
      [ "hierarchy_panel", "classunravel_1_1hierarchy__panel.html", "classunravel_1_1hierarchy__panel" ],
      [ "hiz_pass", "classunravel_1_1hiz__pass.html", "classunravel_1_1hiz__pass" ],
      [ "hub", "classunravel_1_1hub.html", "classunravel_1_1hub" ],
      [ "id_component", "structunravel_1_1id__component.html", "structunravel_1_1id__component" ],
      [ "imgui_interface", "classunravel_1_1imgui__interface.html", "classunravel_1_1imgui__interface" ],
      [ "imgui_panels", "classunravel_1_1imgui__panels.html", "classunravel_1_1imgui__panels" ],
      [ "init_error", "structunravel_1_1init__error.html", "structunravel_1_1init__error" ],
      [ "input_system", "structunravel_1_1input__system.html", "structunravel_1_1input__system" ],
      [ "inspect_result", "structunravel_1_1inspect__result.html", "structunravel_1_1inspect__result" ],
      [ "inspector", "structunravel_1_1inspector.html", "structunravel_1_1inspector" ],
      [ "inspector_alignment", "structunravel_1_1inspector__alignment.html", "structunravel_1_1inspector__alignment" ],
      [ "inspector_asset_handle", "structunravel_1_1inspector__asset__handle.html", "structunravel_1_1inspector__asset__handle" ],
      [ "inspector_asset_handle_animation", "structunravel_1_1inspector__asset__handle__animation.html", "structunravel_1_1inspector__asset__handle__animation" ],
      [ "inspector_asset_handle_audio_clip", "structunravel_1_1inspector__asset__handle__audio__clip.html", "structunravel_1_1inspector__asset__handle__audio__clip" ],
      [ "inspector_asset_handle_font", "structunravel_1_1inspector__asset__handle__font.html", "structunravel_1_1inspector__asset__handle__font" ],
      [ "inspector_asset_handle_material", "structunravel_1_1inspector__asset__handle__material.html", "structunravel_1_1inspector__asset__handle__material" ],
      [ "inspector_asset_handle_mesh", "structunravel_1_1inspector__asset__handle__mesh.html", "structunravel_1_1inspector__asset__handle__mesh" ],
      [ "inspector_asset_handle_physics_material", "structunravel_1_1inspector__asset__handle__physics__material.html", "structunravel_1_1inspector__asset__handle__physics__material" ],
      [ "inspector_asset_handle_prefab", "structunravel_1_1inspector__asset__handle__prefab.html", "structunravel_1_1inspector__asset__handle__prefab" ],
      [ "inspector_asset_handle_scene_prefab", "structunravel_1_1inspector__asset__handle__scene__prefab.html", "structunravel_1_1inspector__asset__handle__scene__prefab" ],
      [ "inspector_asset_handle_style_sheet", "structunravel_1_1inspector__asset__handle__style__sheet.html", "structunravel_1_1inspector__asset__handle__style__sheet" ],
      [ "inspector_asset_handle_texture", "structunravel_1_1inspector__asset__handle__texture.html", "structunravel_1_1inspector__asset__handle__texture" ],
      [ "inspector_asset_handle_ui_tree", "structunravel_1_1inspector__asset__handle__ui__tree.html", "structunravel_1_1inspector__asset__handle__ui__tree" ],
      [ "inspector_bool", "structunravel_1_1inspector__bool.html", "structunravel_1_1inspector__bool" ],
      [ "inspector_bvec2", "structunravel_1_1inspector__bvec2.html", "structunravel_1_1inspector__bvec2" ],
      [ "inspector_bvec3", "structunravel_1_1inspector__bvec3.html", "structunravel_1_1inspector__bvec3" ],
      [ "inspector_bvec4", "structunravel_1_1inspector__bvec4.html", "structunravel_1_1inspector__bvec4" ],
      [ "inspector_color", "structunravel_1_1inspector__color.html", "structunravel_1_1inspector__color" ],
      [ "inspector_double", "structunravel_1_1inspector__double.html", "structunravel_1_1inspector__double" ],
      [ "inspector_duration_sec_double", "structunravel_1_1inspector__duration__sec__double.html", "structunravel_1_1inspector__duration__sec__double" ],
      [ "inspector_duration_sec_float", "structunravel_1_1inspector__duration__sec__float.html", "structunravel_1_1inspector__duration__sec__float" ],
      [ "inspector_entity", "structunravel_1_1inspector__entity.html", "structunravel_1_1inspector__entity" ],
      [ "inspector_float", "structunravel_1_1inspector__float.html", "structunravel_1_1inspector__float" ],
      [ "inspector_int16", "structunravel_1_1inspector__int16.html", "structunravel_1_1inspector__int16" ],
      [ "inspector_int32", "structunravel_1_1inspector__int32.html", "structunravel_1_1inspector__int32" ],
      [ "inspector_int64", "structunravel_1_1inspector__int64.html", "structunravel_1_1inspector__int64" ],
      [ "inspector_int8", "structunravel_1_1inspector__int8.html", "structunravel_1_1inspector__int8" ],
      [ "inspector_layer", "structunravel_1_1inspector__layer.html", "structunravel_1_1inspector__layer" ],
      [ "inspector_light_component", "structunravel_1_1inspector__light__component.html", "structunravel_1_1inspector__light__component" ],
      [ "inspector_mono_object", "structunravel_1_1inspector__mono__object.html", "structunravel_1_1inspector__mono__object" ],
      [ "inspector_mono_scoped_object", "structunravel_1_1inspector__mono__scoped__object.html", "structunravel_1_1inspector__mono__scoped__object" ],
      [ "inspector_panel", "classunravel_1_1inspector__panel.html", "classunravel_1_1inspector__panel" ],
      [ "inspector_path", "structunravel_1_1inspector__path.html", "structunravel_1_1inspector__path" ],
      [ "inspector_physics_compound_shape", "structunravel_1_1inspector__physics__compound__shape.html", "structunravel_1_1inspector__physics__compound__shape" ],
      [ "inspector_prefab_component", "structunravel_1_1inspector__prefab__component.html", "structunravel_1_1inspector__prefab__component" ],
      [ "inspector_quaternion", "structunravel_1_1inspector__quaternion.html", "structunravel_1_1inspector__quaternion" ],
      [ "inspector_range_double", "structunravel_1_1inspector__range__double.html", "structunravel_1_1inspector__range__double" ],
      [ "inspector_range_float", "structunravel_1_1inspector__range__float.html", "structunravel_1_1inspector__range__float" ],
      [ "inspector_range_int16", "structunravel_1_1inspector__range__int16.html", "structunravel_1_1inspector__range__int16" ],
      [ "inspector_range_int32", "structunravel_1_1inspector__range__int32.html", "structunravel_1_1inspector__range__int32" ],
      [ "inspector_range_int64", "structunravel_1_1inspector__range__int64.html", "structunravel_1_1inspector__range__int64" ],
      [ "inspector_range_int8", "structunravel_1_1inspector__range__int8.html", "structunravel_1_1inspector__range__int8" ],
      [ "inspector_range_uint16", "structunravel_1_1inspector__range__uint16.html", "structunravel_1_1inspector__range__uint16" ],
      [ "inspector_range_uint32", "structunravel_1_1inspector__range__uint32.html", "structunravel_1_1inspector__range__uint32" ],
      [ "inspector_range_uint64", "structunravel_1_1inspector__range__uint64.html", "structunravel_1_1inspector__range__uint64" ],
      [ "inspector_range_uint8", "structunravel_1_1inspector__range__uint8.html", "structunravel_1_1inspector__range__uint8" ],
      [ "inspector_registry", "structunravel_1_1inspector__registry.html", "structunravel_1_1inspector__registry" ],
      [ "inspector_resolution_settings", "structunravel_1_1inspector__resolution__settings.html", "structunravel_1_1inspector__resolution__settings" ],
      [ "inspector_shared_material", "structunravel_1_1inspector__shared__material.html", "structunravel_1_1inspector__shared__material" ],
      [ "inspector_size_double", "structunravel_1_1inspector__size__double.html", "structunravel_1_1inspector__size__double" ],
      [ "inspector_size_float", "structunravel_1_1inspector__size__float.html", "structunravel_1_1inspector__size__float" ],
      [ "inspector_size_int16", "structunravel_1_1inspector__size__int16.html", "structunravel_1_1inspector__size__int16" ],
      [ "inspector_size_int32", "structunravel_1_1inspector__size__int32.html", "structunravel_1_1inspector__size__int32" ],
      [ "inspector_size_int64", "structunravel_1_1inspector__size__int64.html", "structunravel_1_1inspector__size__int64" ],
      [ "inspector_size_int8", "structunravel_1_1inspector__size__int8.html", "structunravel_1_1inspector__size__int8" ],
      [ "inspector_size_uint16", "structunravel_1_1inspector__size__uint16.html", "structunravel_1_1inspector__size__uint16" ],
      [ "inspector_size_uint32", "structunravel_1_1inspector__size__uint32.html", "structunravel_1_1inspector__size__uint32" ],
      [ "inspector_size_uint64", "structunravel_1_1inspector__size__uint64.html", "structunravel_1_1inspector__size__uint64" ],
      [ "inspector_size_uint8", "structunravel_1_1inspector__size__uint8.html", "structunravel_1_1inspector__size__uint8" ],
      [ "inspector_string", "structunravel_1_1inspector__string.html", "structunravel_1_1inspector__string" ],
      [ "inspector_text_style", "structunravel_1_1inspector__text__style.html", "structunravel_1_1inspector__text__style" ],
      [ "inspector_text_style_flags", "structunravel_1_1inspector__text__style__flags.html", "structunravel_1_1inspector__text__style__flags" ],
      [ "inspector_transform", "structunravel_1_1inspector__transform.html", "structunravel_1_1inspector__transform" ],
      [ "inspector_uint16", "structunravel_1_1inspector__uint16.html", "structunravel_1_1inspector__uint16" ],
      [ "inspector_uint32", "structunravel_1_1inspector__uint32.html", "structunravel_1_1inspector__uint32" ],
      [ "inspector_uint64", "structunravel_1_1inspector__uint64.html", "structunravel_1_1inspector__uint64" ],
      [ "inspector_uint8", "structunravel_1_1inspector__uint8.html", "structunravel_1_1inspector__uint8" ],
      [ "inspector_uuid", "structunravel_1_1inspector__uuid.html", "structunravel_1_1inspector__uuid" ],
      [ "inspector_vec2", "structunravel_1_1inspector__vec2.html", "structunravel_1_1inspector__vec2" ],
      [ "inspector_vec3", "structunravel_1_1inspector__vec3.html", "structunravel_1_1inspector__vec3" ],
      [ "inspector_vec4", "structunravel_1_1inspector__vec4.html", "structunravel_1_1inspector__vec4" ],
      [ "layer_component", "structunravel_1_1layer__component.html", "structunravel_1_1layer__component" ],
      [ "layer_mask", "structunravel_1_1layer__mask.html", "structunravel_1_1layer__mask" ],
      [ "light", "structunravel_1_1light.html", "structunravel_1_1light" ],
      [ "light_component", "classunravel_1_1light__component.html", "classunravel_1_1light__component" ],
      [ "load_context", "structunravel_1_1load__context.html", "structunravel_1_1load__context" ],
      [ "log_stopwatch", "structunravel_1_1log__stopwatch.html", "structunravel_1_1log__stopwatch" ],
      [ "logging", "structunravel_1_1logging.html", "structunravel_1_1logging" ],
      [ "manifold_point", "structunravel_1_1manifold__point.html", "structunravel_1_1manifold__point" ],
      [ "material", "classunravel_1_1material.html", "classunravel_1_1material" ],
      [ "mesh", "classunravel_1_1mesh.html", "classunravel_1_1mesh" ],
      [ "mesh_importer_meta", "structunravel_1_1mesh__importer__meta.html", "structunravel_1_1mesh__importer__meta" ],
      [ "meta_any_proxy", "structunravel_1_1meta__any__proxy.html", "structunravel_1_1meta__any__proxy" ],
      [ "model", "classunravel_1_1model.html", "classunravel_1_1model" ],
      [ "model_component", "classunravel_1_1model__component.html", "classunravel_1_1model__component" ],
      [ "model_system", "classunravel_1_1model__system.html", "classunravel_1_1model__system" ],
      [ "mono_field_proxy", "structunravel_1_1mono__field__proxy.html", "structunravel_1_1mono__field__proxy" ],
      [ "mono_inspector", "structunravel_1_1mono__inspector.html", null ],
      [ "mono_inspector< asset_handle< T > >", "structunravel_1_1mono__inspector_3_01asset__handle_3_01_t_01_4_01_4.html", null ],
      [ "mono_inspector< entt::handle >", "structunravel_1_1mono__inspector_3_01entt_1_1handle_01_4.html", null ],
      [ "mono_inspector< mono::mono_array< T > >", "structunravel_1_1mono__inspector_3_01mono_1_1mono__array_3_01_t_01_4_01_4.html", null ],
      [ "mono_inspector_enum", "structunravel_1_1mono__inspector__enum.html", null ],
      [ "mono_loader", "structunravel_1_1mono__loader.html", null ],
      [ "mono_loader< Archive, asset_handle< T > >", "structunravel_1_1mono__loader_3_01_archive_00_01asset__handle_3_01_t_01_4_01_4.html", null ],
      [ "mono_loader< Archive, entt::entity >", "structunravel_1_1mono__loader_3_01_archive_00_01entt_1_1entity_01_4.html", null ],
      [ "mono_property_proxy", "structunravel_1_1mono__property__proxy.html", "structunravel_1_1mono__property__proxy" ],
      [ "mono_saver", "structunravel_1_1mono__saver.html", null ],
      [ "mono_saver< Archive, asset_handle< T > >", "structunravel_1_1mono__saver_3_01_archive_00_01asset__handle_3_01_t_01_4_01_4.html", null ],
      [ "mono_saver< Archive, entt::entity >", "structunravel_1_1mono__saver_3_01_archive_00_01entt_1_1entity_01_4.html", null ],
      [ "named_anim", "structunravel_1_1named__anim.html", "structunravel_1_1named__anim" ],
      [ "owned_component", "classunravel_1_1owned__component.html", "classunravel_1_1owned__component" ],
      [ "pbr_material", "classunravel_1_1pbr__material.html", "classunravel_1_1pbr__material" ],
      [ "performance_profiler", "classunravel_1_1performance__profiler.html", "classunravel_1_1performance__profiler" ],
      [ "physics_box_shape", "structunravel_1_1physics__box__shape.html", "structunravel_1_1physics__box__shape" ],
      [ "physics_capsule_shape", "structunravel_1_1physics__capsule__shape.html", "structunravel_1_1physics__capsule__shape" ],
      [ "physics_component", "classunravel_1_1physics__component.html", "classunravel_1_1physics__component" ],
      [ "physics_compound_shape", "structunravel_1_1physics__compound__shape.html", "structunravel_1_1physics__compound__shape" ],
      [ "physics_cylinder_shape", "structunravel_1_1physics__cylinder__shape.html", "structunravel_1_1physics__cylinder__shape" ],
      [ "physics_material", "structunravel_1_1physics__material.html", "structunravel_1_1physics__material" ],
      [ "physics_sphere_shape", "structunravel_1_1physics__sphere__shape.html", "structunravel_1_1physics__sphere__shape" ],
      [ "physics_system", "classunravel_1_1physics__system.html", "classunravel_1_1physics__system" ],
      [ "picking_manager", "classunravel_1_1picking__manager.html", "classunravel_1_1picking__manager" ],
      [ "pipeline_camera", "classunravel_1_1pipeline__camera.html", "classunravel_1_1pipeline__camera" ],
      [ "pose_mat4", "structunravel_1_1pose__mat4.html", "structunravel_1_1pose__mat4" ],
      [ "pose_transform", "structunravel_1_1pose__transform.html", "structunravel_1_1pose__transform" ],
      [ "prefab", "structunravel_1_1prefab.html", "structunravel_1_1prefab" ],
      [ "prefab_component", "structunravel_1_1prefab__component.html", "structunravel_1_1prefab__component" ],
      [ "prefab_id_component", "structunravel_1_1prefab__id__component.html", "structunravel_1_1prefab__id__component" ],
      [ "prefab_override_context", "structunravel_1_1prefab__override__context.html", "structunravel_1_1prefab__override__context" ],
      [ "prefab_property_override", "structunravel_1_1prefab__property__override.html", "structunravel_1_1prefab__property__override" ],
      [ "prefab_property_override_data", "structunravel_1_1prefab__property__override__data.html", "structunravel_1_1prefab__property__override__data" ],
      [ "prefilter_pass", "classunravel_1_1prefilter__pass.html", "classunravel_1_1prefilter__pass" ],
      [ "project_manager", "classunravel_1_1project__manager.html", "classunravel_1_1project__manager" ],
      [ "project_settings_panel", "classunravel_1_1project__settings__panel.html", "classunravel_1_1project__settings__panel" ],
      [ "property_action_t", "structunravel_1_1property__action__t.html", "structunravel_1_1property__action__t" ],
      [ "property_layout", "classunravel_1_1property__layout.html", "classunravel_1_1property__layout" ],
      [ "property_path_context", "classunravel_1_1property__path__context.html", "classunravel_1_1property__path__context" ],
      [ "raycast_hit", "structunravel_1_1raycast__hit.html", "structunravel_1_1raycast__hit" ],
      [ "reflection_probe", "structunravel_1_1reflection__probe.html", "structunravel_1_1reflection__probe" ],
      [ "reflection_probe_component", "classunravel_1_1reflection__probe__component.html", "classunravel_1_1reflection__probe__component" ],
      [ "reflection_probe_system", "classunravel_1_1reflection__probe__system.html", "classunravel_1_1reflection__probe__system" ],
      [ "render_window", "structunravel_1_1render__window.html", "structunravel_1_1render__window" ],
      [ "renderer", "structunravel_1_1renderer.html", "structunravel_1_1renderer" ],
      [ "rendering_system", "classunravel_1_1rendering__system.html", "classunravel_1_1rendering__system" ],
      [ "rich_segment", "structunravel_1_1rich__segment.html", "structunravel_1_1rich__segment" ],
      [ "rich_state", "structunravel_1_1rich__state.html", "structunravel_1_1rich__state" ],
      [ "RmlUi_FileInterface", "classunravel_1_1_rml_ui___file_interface.html", "classunravel_1_1_rml_ui___file_interface" ],
      [ "RmlUi_RenderInterface", "classunravel_1_1_rml_ui___render_interface.html", "classunravel_1_1_rml_ui___render_interface" ],
      [ "RmlUi_SystemInterface", "classunravel_1_1_rml_ui___system_interface.html", "classunravel_1_1_rml_ui___system_interface" ],
      [ "root_component", "structunravel_1_1root__component.html", "structunravel_1_1root__component" ],
      [ "root_motion_params", "structunravel_1_1root__motion__params.html", "structunravel_1_1root__motion__params" ],
      [ "save_context", "structunravel_1_1save__context.html", "structunravel_1_1save__context" ],
      [ "scaled_font", "structunravel_1_1scaled__font.html", null ],
      [ "scene", "structunravel_1_1scene.html", "structunravel_1_1scene" ],
      [ "scene_panel", "classunravel_1_1scene__panel.html", "classunravel_1_1scene__panel" ],
      [ "scene_prefab", "structunravel_1_1scene__prefab.html", null ],
      [ "scope_perf_timer", "classunravel_1_1scope__perf__timer.html", "classunravel_1_1scope__perf__timer" ],
      [ "scratch_cache", "structunravel_1_1scratch__cache.html", "structunravel_1_1scratch__cache" ],
      [ "script", "structunravel_1_1script.html", "structunravel_1_1script" ],
      [ "script_component", "classunravel_1_1script__component.html", "classunravel_1_1script__component" ],
      [ "script_library", "structunravel_1_1script__library.html", "structunravel_1_1script__library" ],
      [ "script_system", "structunravel_1_1script__system.html", "structunravel_1_1script__system" ],
      [ "settings", "structunravel_1_1settings.html", "structunravel_1_1settings" ],
      [ "simulation", "structunravel_1_1simulation.html", "structunravel_1_1simulation" ],
      [ "skin_bind_data", "classunravel_1_1skin__bind__data.html", "classunravel_1_1skin__bind__data" ],
      [ "skylight_component", "classunravel_1_1skylight__component.html", "classunravel_1_1skylight__component" ],
      [ "ssr_component", "classunravel_1_1ssr__component.html", "classunravel_1_1ssr__component" ],
      [ "ssr_pass", "classunravel_1_1ssr__pass.html", "classunravel_1_1ssr__pass" ],
      [ "statistics_panel", "classunravel_1_1statistics__panel.html", "classunravel_1_1statistics__panel" ],
      [ "style_panel", "classunravel_1_1style__panel.html", "classunravel_1_1style__panel" ],
      [ "style_sheet", "structunravel_1_1style__sheet.html", "structunravel_1_1style__sheet" ],
      [ "submesh_component", "structunravel_1_1submesh__component.html", "structunravel_1_1submesh__component" ],
      [ "tag_component", "structunravel_1_1tag__component.html", "structunravel_1_1tag__component" ],
      [ "test_component", "structunravel_1_1test__component.html", "structunravel_1_1test__component" ],
      [ "text_buffer", "structunravel_1_1text__buffer.html", "structunravel_1_1text__buffer" ],
      [ "text_buffer_builder", "structunravel_1_1text__buffer__builder.html", "structunravel_1_1text__buffer__builder" ],
      [ "text_component", "classunravel_1_1text__component.html", "classunravel_1_1text__component" ],
      [ "text_line", "structunravel_1_1text__line.html", "structunravel_1_1text__line" ],
      [ "text_metrics", "structunravel_1_1text__metrics.html", "structunravel_1_1text__metrics" ],
      [ "text_style", "structunravel_1_1text__style.html", "structunravel_1_1text__style" ],
      [ "text_style_flags", "structunravel_1_1text__style__flags.html", "structunravel_1_1text__style__flags" ],
      [ "texture_importer_meta", "structunravel_1_1texture__importer__meta.html", "structunravel_1_1texture__importer__meta" ],
      [ "threader", "structunravel_1_1threader.html", "structunravel_1_1threader" ],
      [ "thumbnail_manager", "structunravel_1_1thumbnail__manager.html", "structunravel_1_1thumbnail__manager" ],
      [ "tonemapping_component", "classunravel_1_1tonemapping__component.html", "classunravel_1_1tonemapping__component" ],
      [ "tonemapping_pass", "classunravel_1_1tonemapping__pass.html", "classunravel_1_1tonemapping__pass" ],
      [ "tracked_lambda_action_t", "structunravel_1_1tracked__lambda__action__t.html", "structunravel_1_1tracked__lambda__action__t" ],
      [ "transform_component", "classunravel_1_1transform__component.html", "classunravel_1_1transform__component" ],
      [ "transform_move_action_t", "structunravel_1_1transform__move__action__t.html", "structunravel_1_1transform__move__action__t" ],
      [ "transform_move_global_action_t", "structunravel_1_1transform__move__global__action__t.html", "structunravel_1_1transform__move__global__action__t" ],
      [ "transform_rotate_action_t", "structunravel_1_1transform__rotate__action__t.html", "structunravel_1_1transform__rotate__action__t" ],
      [ "transform_scale_action_t", "structunravel_1_1transform__scale__action__t.html", "structunravel_1_1transform__scale__action__t" ],
      [ "transform_skew_action_t", "structunravel_1_1transform__skew__action__t.html", "structunravel_1_1transform__skew__action__t" ],
      [ "transform_system", "classunravel_1_1transform__system.html", "classunravel_1_1transform__system" ],
      [ "ui_document_component", "structunravel_1_1ui__document__component.html", "structunravel_1_1ui__document__component" ],
      [ "ui_events", "structunravel_1_1ui__events.html", "structunravel_1_1ui__events" ],
      [ "ui_system", "structunravel_1_1ui__system.html", "structunravel_1_1ui__system" ],
      [ "ui_tree", "structunravel_1_1ui__tree.html", "structunravel_1_1ui__tree" ],
      [ "undo_redo_panel", "classunravel_1_1undo__redo__panel.html", "classunravel_1_1undo__redo__panel" ],
      [ "undo_redo_stack", "structunravel_1_1undo__redo__stack.html", "structunravel_1_1undo__redo__stack" ],
      [ "uniforms_cache", "structunravel_1_1uniforms__cache.html", "structunravel_1_1uniforms__cache" ],
      [ "untracked_action_t", "structunravel_1_1untracked__action__t.html", "structunravel_1_1untracked__action__t" ],
      [ "var_info", "structunravel_1_1var__info.html", "structunravel_1_1var__info" ],
      [ "word_frag", "structunravel_1_1word__frag.html", "structunravel_1_1word__frag" ],
      [ "wrapped_line", "structunravel_1_1wrapped__line.html", "structunravel_1_1wrapped__line" ]
    ] ],
    [ "utf8", "namespaceutf8.html", [
      [ "unchecked", "namespaceutf8_1_1unchecked.html", [
        [ "iterator", "classutf8_1_1unchecked_1_1iterator.html", "classutf8_1_1unchecked_1_1iterator" ]
      ] ],
      [ "exception", "classutf8_1_1exception.html", null ],
      [ "invalid_code_point", "classutf8_1_1invalid__code__point.html", "classutf8_1_1invalid__code__point" ],
      [ "invalid_utf16", "classutf8_1_1invalid__utf16.html", "classutf8_1_1invalid__utf16" ],
      [ "invalid_utf8", "classutf8_1_1invalid__utf8.html", "classutf8_1_1invalid__utf8" ],
      [ "iterator", "classutf8_1_1iterator.html", "classutf8_1_1iterator" ],
      [ "not_enough_room", "classutf8_1_1not__enough__room.html", "classutf8_1_1not__enough__room" ]
    ] ],
    [ "asset_handle", "structasset__handle.html", "structasset__handle" ],
    [ "asset_link", "structasset__link.html", "structasset__link" ],
    [ "Attrib", "struct_attrib.html", "struct_attrib" ],
    [ "AviWriter", "struct_avi_writer.html", "struct_avi_writer" ],
    [ "Axis", "struct_axis.html", "struct_axis" ],
    [ "checked_array_deleter", "structchecked__array__deleter.html", "structchecked__array__deleter" ],
    [ "checked_deleter", "structchecked__deleter.html", "structchecked__deleter" ],
    [ "crtp_meta_type", "structcrtp__meta__type.html", "structcrtp__meta__type" ],
    [ "DdVertex", "struct_dd_vertex.html", "struct_dd_vertex" ],
    [ "DebugDrawEncoder", "struct_debug_draw_encoder.html", "struct_debug_draw_encoder" ],
    [ "DebugDrawEncoderImpl", "struct_debug_draw_encoder_impl.html", "struct_debug_draw_encoder_impl" ],
    [ "DebugDrawEncoderScopePush", "class_debug_draw_encoder_scope_push.html", "class_debug_draw_encoder_scope_push" ],
    [ "DebugDrawShared", "struct_debug_draw_shared.html", "struct_debug_draw_shared" ],
    [ "DebugMesh", "struct_debug_mesh.html", "struct_debug_mesh" ],
    [ "DebugMeshVertex", "struct_debug_mesh_vertex.html", "struct_debug_mesh_vertex" ],
    [ "DebugShapeVertex", "struct_debug_shape_vertex.html", "struct_debug_shape_vertex" ],
    [ "DebugUvVertex", "struct_debug_uv_vertex.html", "struct_debug_uv_vertex" ],
    [ "DebugVertex", "struct_debug_vertex.html", "struct_debug_vertex" ],
    [ "FontRangeMerge", "struct_font_range_merge.html", "struct_font_range_merge" ],
    [ "GeometryHandle", "struct_geometry_handle.html", "struct_geometry_handle" ],
    [ "GeometryT", "struct_geometry_t.html", "struct_geometry_t" ],
    [ "ImGui_ImplOSPP_Data", "struct_im_gui___impl_o_s_p_p___data.html", "struct_im_gui___impl_o_s_p_p___data" ],
    [ "ImGui_ImplOSPP_ViewportData", "struct_im_gui___impl_o_s_p_p___viewport_data.html", "struct_im_gui___impl_o_s_p_p___viewport_data" ],
    [ "ImGuiToast", "class_im_gui_toast.html", "class_im_gui_toast" ],
    [ "module_data", "structmodule__data.html", "structmodule__data" ],
    [ "module_desc", "structmodule__desc.html", "structmodule__desc" ],
    [ "OcornutImguiContext", "struct_ocornut_imgui_context.html", "struct_ocornut_imgui_context" ],
    [ "Pack2D", "struct_pack2_d.html", "struct_pack2_d" ],
    [ "PackCube", "struct_pack_cube.html", "struct_pack_cube" ],
    [ "point", "structpoint.html", "structpoint" ],
    [ "Program", "struct_program.html", "struct_program" ],
    [ "range", "structrange.html", "structrange" ],
    [ "rect", "structrect.html", "structrect" ],
    [ "RectPack2DT", "class_rect_pack2_d_t.html", "class_rect_pack2_d_t" ],
    [ "RectPackCubeT", "class_rect_pack_cube_t.html", "class_rect_pack_cube_t" ],
    [ "rendering_pipeline", "classrendering__pipeline.html", null ],
    [ "service", "structservice.html", "structservice" ],
    [ "size", "structsize.html", "structsize" ],
    [ "SpriteHandle", "struct_sprite_handle.html", "struct_sprite_handle" ],
    [ "SpriteT", "struct_sprite_t.html", "struct_sprite_t" ],
    [ "StaticAssert", "struct_static_assert.html", null ],
    [ "StaticAssert< true >", "struct_static_assert_3_01true_01_4.html", null ],
    [ "subprocess_s", "structsubprocess__s.html", "structsubprocess__s" ]
];