var dir_86d01881e271a3bf02ddb1a66609fdde =
[
    [ "font_manager.cpp", "font__manager_8cpp.html", "font__manager_8cpp" ],
    [ "font_manager.h", "font__manager_8h.html", "font__manager_8h" ],
    [ "fs_font_basic.bin.h", "fs__font__basic_8bin_8h.html", "fs__font__basic_8bin_8h" ],
    [ "fs_font_distance_field.bin.h", "fs__font__distance__field_8bin_8h.html", "fs__font__distance__field_8bin_8h" ],
    [ "fs_font_distance_field_drop_shadow.bin.h", "fs__font__distance__field__drop__shadow_8bin_8h.html", "fs__font__distance__field__drop__shadow_8bin_8h" ],
    [ "fs_font_distance_field_drop_shadow_image.bin.h", "fs__font__distance__field__drop__shadow__image_8bin_8h.html", "fs__font__distance__field__drop__shadow__image_8bin_8h" ],
    [ "fs_font_distance_field_outline.bin.h", "fs__font__distance__field__outline_8bin_8h.html", "fs__font__distance__field__outline_8bin_8h" ],
    [ "fs_font_distance_field_outline_drop_shadow_image.bin.h", "fs__font__distance__field__outline__drop__shadow__image_8bin_8h.html", "fs__font__distance__field__outline__drop__shadow__image_8bin_8h" ],
    [ "fs_font_distance_field_outline_image.bin.h", "fs__font__distance__field__outline__image_8bin_8h.html", "fs__font__distance__field__outline__image_8bin_8h" ],
    [ "fs_font_distance_field_subpixel.bin.h", "fs__font__distance__field__subpixel_8bin_8h.html", "fs__font__distance__field__subpixel_8bin_8h" ],
    [ "sdf.h", "sdf_8h.html", "sdf_8h" ],
    [ "text_buffer_manager.cpp", "text__buffer__manager_8cpp.html", "text__buffer__manager_8cpp" ],
    [ "text_buffer_manager.h", "text__buffer__manager_8h.html", "text__buffer__manager_8h" ],
    [ "text_metrics.cpp", "text__metrics_8cpp.html", null ],
    [ "text_metrics.h", "text__metrics_8h.html", "text__metrics_8h" ],
    [ "utf8.cpp", "utf8_8cpp.html", "utf8_8cpp" ],
    [ "utf8.h", "graphics_2utils_2font_2utf8_8h.html", "graphics_2utils_2font_2utf8_8h" ],
    [ "vs_font_basic.bin.h", "vs__font__basic_8bin_8h.html", "vs__font__basic_8bin_8h" ],
    [ "vs_font_distance_field.bin.h", "vs__font__distance__field_8bin_8h.html", "vs__font__distance__field_8bin_8h" ],
    [ "vs_font_distance_field_drop_shadow.bin.h", "vs__font__distance__field__drop__shadow_8bin_8h.html", "vs__font__distance__field__drop__shadow_8bin_8h" ],
    [ "vs_font_distance_field_drop_shadow_image.bin.h", "vs__font__distance__field__drop__shadow__image_8bin_8h.html", "vs__font__distance__field__drop__shadow__image_8bin_8h" ],
    [ "vs_font_distance_field_outline.bin.h", "vs__font__distance__field__outline_8bin_8h.html", "vs__font__distance__field__outline_8bin_8h" ],
    [ "vs_font_distance_field_outline_drop_shadow_image.bin.h", "vs__font__distance__field__outline__drop__shadow__image_8bin_8h.html", "vs__font__distance__field__outline__drop__shadow__image_8bin_8h" ],
    [ "vs_font_distance_field_outline_image.bin.h", "vs__font__distance__field__outline__image_8bin_8h.html", "vs__font__distance__field__outline__image_8bin_8h" ],
    [ "vs_font_distance_field_subpixel.bin.h", "vs__font__distance__field__subpixel_8bin_8h.html", "vs__font__distance__field__subpixel_8bin_8h" ]
];