var namespacemoodycamel_1_1details =
[
    [ "_hash_32_or_64", "structmoodycamel_1_1details_1_1__hash__32__or__64.html", null ],
    [ "_hash_32_or_64< 1 >", "structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4.html", null ],
    [ "ConcurrentQueueProducerTypelessBase", "structmoodycamel_1_1details_1_1_concurrent_queue_producer_typeless_base.html", "structmoodycamel_1_1details_1_1_concurrent_queue_producer_typeless_base" ],
    [ "const_numeric_max", "structmoodycamel_1_1details_1_1const__numeric__max.html", null ],
    [ "hash_32_or_64", "structmoodycamel_1_1details_1_1hash__32__or__64.html", null ],
    [ "identity", "structmoodycamel_1_1details_1_1identity.html", "structmoodycamel_1_1details_1_1identity" ],
    [ "is_trivially_destructible", "structmoodycamel_1_1details_1_1is__trivially__destructible.html", null ],
    [ "max_align_t", "unionmoodycamel_1_1details_1_1max__align__t.html", "unionmoodycamel_1_1details_1_1max__align__t" ],
    [ "nomove_if", "structmoodycamel_1_1details_1_1nomove__if.html", null ],
    [ "nomove_if< false >", "structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4.html", null ],
    [ "static_is_lock_free", "structmoodycamel_1_1details_1_1static__is__lock__free.html", null ],
    [ "static_is_lock_free< bool >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01bool_01_4.html", null ],
    [ "static_is_lock_free< U * >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01_u_01_5_01_4.html", null ],
    [ "static_is_lock_free_num", "structmoodycamel_1_1details_1_1static__is__lock__free__num.html", null ],
    [ "static_is_lock_free_num< int >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01int_01_4.html", null ],
    [ "static_is_lock_free_num< long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01_4.html", null ],
    [ "static_is_lock_free_num< long long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01long_01_4.html", null ],
    [ "static_is_lock_free_num< short >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01short_01_4.html", null ],
    [ "static_is_lock_free_num< signed char >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01signed_01char_01_4.html", null ],
    [ "thread_id_converter", "structmoodycamel_1_1details_1_1thread__id__converter.html", "structmoodycamel_1_1details_1_1thread__id__converter" ],
    [ "ThreadExitListener", "structmoodycamel_1_1details_1_1_thread_exit_listener.html", "structmoodycamel_1_1details_1_1_thread_exit_listener" ],
    [ "ThreadExitNotifier", "classmoodycamel_1_1details_1_1_thread_exit_notifier.html", null ],
    [ "std_max_align_t", "namespacemoodycamel_1_1details.html#a61cb412cfd41b7cf23ad9338cb850aee", null ],
    [ "thread_id_t", "namespacemoodycamel_1_1details.html#af2f0ffefbd01d4921bb4a89353b30018", null ],
    [ "thread_id", "namespacemoodycamel_1_1details.html#a137f928bff88e1486d82701dea45164b", null ]
];