var shadow_8h =
[
    [ "unravel::shadow::LightType", "structunravel_1_1shadow_1_1_light_type.html", "structunravel_1_1shadow_1_1_light_type" ],
    [ "unravel::shadow::DepthImpl", "structunravel_1_1shadow_1_1_depth_impl.html", "structunravel_1_1shadow_1_1_depth_impl" ],
    [ "unravel::shadow::PackDepth", "structunravel_1_1shadow_1_1_pack_depth.html", "structunravel_1_1shadow_1_1_pack_depth" ],
    [ "unravel::shadow::SmImpl", "structunravel_1_1shadow_1_1_sm_impl.html", "structunravel_1_1shadow_1_1_sm_impl" ],
    [ "unravel::shadow::SmType", "structunravel_1_1shadow_1_1_sm_type.html", "structunravel_1_1shadow_1_1_sm_type" ],
    [ "unravel::shadow::TetrahedronFaces", "structunravel_1_1shadow_1_1_tetrahedron_faces.html", "structunravel_1_1shadow_1_1_tetrahedron_faces" ],
    [ "unravel::shadow::ProjType", "structunravel_1_1shadow_1_1_proj_type.html", "structunravel_1_1shadow_1_1_proj_type" ],
    [ "unravel::shadow::ShadowMapRenderTargets", "structunravel_1_1shadow_1_1_shadow_map_render_targets.html", "structunravel_1_1shadow_1_1_shadow_map_render_targets" ],
    [ "unravel::shadow::PosNormalTexcoordVertex", "structunravel_1_1shadow_1_1_pos_normal_texcoord_vertex.html", "structunravel_1_1shadow_1_1_pos_normal_texcoord_vertex" ],
    [ "unravel::shadow::Light", "structunravel_1_1shadow_1_1_light.html", "structunravel_1_1shadow_1_1_light" ],
    [ "unravel::shadow::Light::Position", "unionunravel_1_1shadow_1_1_light_1_1_position.html", "unionunravel_1_1shadow_1_1_light_1_1_position" ],
    [ "unravel::shadow::Light::SpotDirectionInner", "unionunravel_1_1shadow_1_1_light_1_1_spot_direction_inner.html", "unionunravel_1_1shadow_1_1_light_1_1_spot_direction_inner" ],
    [ "unravel::shadow::Uniforms", "structunravel_1_1shadow_1_1_uniforms.html", "structunravel_1_1shadow_1_1_uniforms" ],
    [ "unravel::shadow::RenderState", "structunravel_1_1shadow_1_1_render_state.html", "structunravel_1_1shadow_1_1_render_state" ],
    [ "unravel::shadow::PosColorTexCoord0Vertex", "structunravel_1_1shadow_1_1_pos_color_tex_coord0_vertex.html", "structunravel_1_1shadow_1_1_pos_color_tex_coord0_vertex" ],
    [ "unravel::shadow::PosVertex", "structunravel_1_1shadow_1_1_pos_vertex.html", "structunravel_1_1shadow_1_1_pos_vertex" ],
    [ "unravel::shadow::Programs", "structunravel_1_1shadow_1_1_programs.html", "structunravel_1_1shadow_1_1_programs" ],
    [ "unravel::shadow::ShadowMapSettings", "structunravel_1_1shadow_1_1_shadow_map_settings.html", "structunravel_1_1shadow_1_1_shadow_map_settings" ],
    [ "unravel::shadow::SceneSettings", "structunravel_1_1shadow_1_1_scene_settings.html", "structunravel_1_1shadow_1_1_scene_settings" ],
    [ "unravel::shadow::ClearValues", "structunravel_1_1shadow_1_1_clear_values.html", "structunravel_1_1shadow_1_1_clear_values" ],
    [ "unravel::shadow::frustum_calculation_method", "structunravel_1_1shadow_1_1frustum__calculation__method.html", "structunravel_1_1shadow_1_1frustum__calculation__method" ],
    [ "unravel::shadow::csm_optimization_flags", "structunravel_1_1shadow_1_1csm__optimization__flags.html", "structunravel_1_1shadow_1_1csm__optimization__flags" ],
    [ "unravel::shadow::adaptive_shadow_params", "structunravel_1_1shadow_1_1adaptive__shadow__params.html", "structunravel_1_1shadow_1_1adaptive__shadow__params" ],
    [ "unravel::shadow::shadowmap_generator", "classunravel_1_1shadow_1_1shadowmap__generator.html", "classunravel_1_1shadow_1_1shadowmap__generator" ],
    [ "SHADOW_FLOAT_PARAM", "shadow_8h.html#a7ba2c489d03760e59b046e56750d2fe0", null ],
    [ "shadow_map_models_t", "shadow_8h.html#a2874fe5cdd35210084393fb17d631be1", null ]
];